(()=>{'use strict';
const storeKey='ma-academy-v1';
const academies=[
{id:'academy.it-support',title:'IT Support Academy',status:'ACTIVE',summary:'A complete beginner-to-job-ready path covering devices, Windows, networking, identity, Microsoft 365 and professional support.',missions:['mission.hardware-triage','mission.windows-performance','mission.network-diagnosis','mission.identity-support','mission.m365-support','mission.ticket-quality'],topics:['topic.hardware','topic.windows-tools','topic.ip-addressing','topic.dns','topic.identity','topic.m365','topic.troubleshooting','topic.ticketing']},
{id:'academy.networking',title:'Networking Academy',status:'FOUNDATION READY',summary:'Understand network services and diagnose connectivity with a repeatable layered method.',missions:['mission.network-diagnosis'],topics:['topic.ip-addressing','topic.dns','topic.dhcp','topic.wifi','topic.troubleshooting']},
{id:'academy.cloud',title:'Cloud Academy',status:'PLANNED',summary:'Prepare shared networking, security and identity knowledge for future cloud operations missions.',missions:[],topics:['topic.dns','topic.identity','topic.security']}
];
const topics=[
{id:'topic.hardware',title:'Computer Hardware and Safety',summary:'CPU, memory, storage, power, peripherals and a safe evidence-first hardware inspection workflow.',tags:['hardware','safety','foundation'],usedBy:['IT Support']},
{id:'topic.windows-tools',title:'Windows Diagnostic Tools',summary:'Task Manager, Event Viewer, Reliability Monitor, Services, Device Manager, SFC and DISM.',tags:['windows','diagnostics'],usedBy:['IT Support']},
{id:'topic.ip-addressing',title:'IP Addressing',summary:'IPv4 addresses, subnet masks, gateways and the boundaries they define.',tags:['networking','tcp-ip'],usedBy:['IT Support','Networking']},
{id:'topic.dns',title:'DNS Resolution',summary:'How names become IP addresses and how to isolate a DNS failure.',tags:['networking','dns','cloud'],usedBy:['IT Support','Networking','Cloud']},
{id:'topic.dhcp',title:'DHCP Configuration',summary:'How clients obtain IP configuration, what APIPA means and how to renew a lease safely.',tags:['networking','dhcp'],usedBy:['IT Support','Networking']},
{id:'topic.wifi',title:'Wi-Fi Troubleshooting',summary:'Signal, SSID, authentication, addressing and layered isolation for wireless failures.',tags:['networking','wifi'],usedBy:['IT Support','Networking']},
{id:'topic.troubleshooting',title:'Evidence-Based Troubleshooting',summary:'Observe, scope, test one cause, verify the result and document evidence.',tags:['support','method'],usedBy:['IT Support','Networking']},
{id:'topic.identity',title:'Identity and Access',summary:'Accounts, groups, authentication, least privilege and safe access changes.',tags:['identity','security'],usedBy:['IT Support','Cloud']},
{id:'topic.m365',title:'Microsoft 365 Support',summary:'Licensing, service health, Outlook isolation, MFA and safe account troubleshooting.',tags:['microsoft-365','outlook','support'],usedBy:['IT Support']},
{id:'topic.security',title:'Support Security Essentials',summary:'Identity verification, phishing awareness, least privilege, escalation and evidence preservation.',tags:['security','support'],usedBy:['IT Support','Cloud']},
{id:'topic.printers',title:'Printer Troubleshooting',summary:'Scope, queues, spooler, drivers, ports and verification for local and network printers.',tags:['printers','support'],usedBy:['IT Support']},
{id:'topic.ticketing',title:'Tickets and Resolution Notes',summary:'Record symptom, impact, evidence, root cause, action, verification and follow-up professionally.',tags:['ticketing','documentation'],usedBy:['IT Support']}
];
const missions=[
{id:'mission.hardware-triage',academy:'IT Support Academy',title:'Triage a No-Display Computer',objective:'Inspect a no-display symptom safely and isolate power, display, memory or graphics causes.',topicIds:['topic.hardware','topic.troubleshooting'],labId:'lab.hardware-triage',steps:['Learn hardware roles and safety','Practice an external-to-internal check sequence','Solve a no-display scenario','Verify with a finding and evidence log'],competency:'Triage a basic hardware failure safely and systematically.',criteria:['Starts with external and power checks','Uses ESD and one-change-at-a-time practice','Records observed evidence and final verification']},
{id:'mission.windows-performance',academy:'IT Support Academy',title:'Diagnose a Slow Windows Computer',objective:'Use built-in Windows tools to identify the resource, startup, service or reliability cause.',topicIds:['topic.windows-tools','topic.troubleshooting'],labId:'lab.windows-performance',steps:['Learn the Windows diagnostic toolkit','Practice reading performance evidence','Solve a slow-startup scenario','Verify with before-and-after evidence'],competency:'Diagnose a Windows performance complaint using built-in evidence.',criteria:['Identifies the constrained resource or failing component','Avoids unnecessary destructive changes','Verifies improvement and documents the result']},
{id:'mission.network-diagnosis',academy:'IT Support Academy · Networking Academy',title:'Diagnose a Name Resolution Failure',objective:'Determine whether a failure is local, network, internet-route or DNS related.',topicIds:['topic.ip-addressing','topic.dhcp','topic.dns','topic.wifi','topic.troubleshooting'],labId:'lab-dns',steps:['Learn IP, gateway, DHCP and DNS boundaries','Practice the diagnostic command sequence','Solve a connected-but-no-sites scenario','Verify with a written evidence table'],competency:'Diagnose basic network and DNS failures using evidence.',criteria:['Tests loopback, local interface, gateway, public IP and DNS','Interprets every result correctly','States the failed boundary and verifies recovery']},
{id:'mission.identity-support',academy:'IT Support Academy',title:'Resolve a User Sign-In Problem',objective:'Scope and resolve a common user sign-in issue without weakening security.',topicIds:['topic.identity','topic.security','topic.troubleshooting'],labId:'lab-ad',steps:['Learn identity, lockout and verification checks','Practice a safe support checklist','Solve a single-user sign-in scenario','Verify with a professional resolution note'],competency:'Triage a user sign-in failure using safe identity procedures.',criteria:['Verifies identity before account action','Checks username, domain, lockout, time and connectivity','Records action and successful sign-in verification']},
{id:'mission.m365-support',academy:'IT Support Academy',title:'Restore Microsoft 365 Access',objective:'Separate service, account, license, MFA, network and desktop-client causes safely.',topicIds:['topic.m365','topic.identity','topic.security','topic.troubleshooting'],labId:'lab.m365-isolation',steps:['Learn account, service and client boundaries','Practice the web-versus-desktop isolation flow','Solve an Outlook sign-in scenario','Verify access without exposing credentials'],competency:'Isolate and resolve a common Microsoft 365 access problem.',criteria:['Checks service health, account and license first','Uses web access to isolate desktop-client issues','Protects credentials and verifies the restored service']},
{id:'mission.ticket-quality',academy:'IT Support Academy',title:'Write a Verifiable Resolution Note',objective:'Turn troubleshooting activity into clear operational evidence.',topicIds:['topic.ticketing','topic.troubleshooting','topic.printers'],labId:'lab-ticket',steps:['Learn the evidence structure','Practice symptom and impact writing','Solve an incomplete printer ticket','Verify with a complete resolution note'],competency:'Document symptom, evidence, cause, action and verification.',criteria:['Includes scope, symptom and exact evidence','States the cause and controlled action','Records technical and user verification']}
];
const lessons=[
{id:'lesson-hardware',phase:1,cat:'foundation',icon:'HW',title:'Computer Hardware Essentials',time:'18 MIN',summary:'Understand the components inside a computer and recognize common hardware symptoms.',sections:[['What you need to know','The CPU processes instructions, RAM holds active working data, storage keeps files, the motherboard connects components, and the power supply provides stable electrical power. A technician identifies the failing layer before replacing parts.'],['Real example','A computer that powers on but shows no display may have a loose display cable, wrong monitor input, RAM seating problem, or graphics failure. Start with external checks before opening the device.'],['Safe workflow','Power down, disconnect power, use ESD precautions, document cable locations, and change only one thing at a time. Never open equipment when doing so violates a warranty or workplace policy.'],['Checkpoint','Explain the difference between RAM and storage. Then identify three reasons a computer may have no display.']]},
{id:'lesson-os',phase:1,cat:'foundation',icon:'OS',title:'Operating System Fundamentals',time:'20 MIN',summary:'Learn how Windows manages hardware, applications, files, users, and services.',sections:[['Core idea','The operating system connects users and applications to hardware. Windows services run background functions, Device Manager shows hardware state, Task Manager shows resource use, and Event Viewer records important events.'],['Useful tools','Open Task Manager with Ctrl + Shift + Esc. Open Run with Win + R. Use msinfo32 for system information, devmgmt.msc for Device Manager, and eventvwr.msc for Event Viewer.'],['Real example','If an application freezes, check Task Manager before restarting the entire computer. Observe CPU, memory, disk, and the application status.'],['Checkpoint','Open Task Manager and identify the three processes currently using the most memory.']]},
{id:'lesson-method',phase:1,cat:'support',icon:'TS',title:'Troubleshooting Method',time:'15 MIN',summary:'Use a repeatable evidence-based process instead of guessing.',sections:[['Six-step process','1. Identify the problem. 2. Establish a probable cause. 3. Test the cause. 4. Plan and implement the fix. 5. Verify full functionality. 6. Document findings and actions.'],['Question quality','Ask what changed, when it started, who is affected, what error appears, what still works, and what has already been tried. These questions narrow the scope.'],['Change control','Before a risky change, consider impact, approval, rollback, and backup. A technically possible fix is not always an operationally safe fix.'],['Checkpoint','Write five questions you would ask a user who says, “The internet is broken.”']]},
{id:'lesson-ip',phase:2,cat:'network',icon:'IP',title:'IP Addressing and TCP/IP',time:'25 MIN',summary:'Understand IP addresses, subnet masks, gateways, ports, TCP, and UDP.',sections:[['Addressing','An IPv4 address identifies an interface. The subnet mask identifies the local network portion. The default gateway routes traffic to other networks. A DNS server translates names into IP addresses.'],['TCP and UDP','TCP confirms delivery and ordering, making it suitable for web sessions, email, and file transfer. UDP has lower overhead and is common for voice, video, and DNS queries.'],['Commands','Use ipconfig /all to inspect configuration. Use ping to test reachability. Use tracert to view the path. Use netstat -ano to inspect connections and listening ports.'],['Command practice','ipconfig /all\nping 127.0.0.1\nping <default-gateway>\ntracert 8.8.8.8']]},
{id:'lesson-dns',phase:2,cat:'network',icon:'DNS',title:'DNS and DHCP',time:'22 MIN',summary:'Learn how devices receive configurations and resolve human-readable names.',sections:[['DHCP','DHCP normally provides an IP address, subnet mask, gateway, and DNS server. The DORA sequence is Discover, Offer, Request, Acknowledge.'],['DNS','DNS resolution commonly checks browser/OS cache, the hosts file, and configured DNS resolvers. A website may fail by name while its server IP remains reachable.'],['Commands','Use ipconfig /release and ipconfig /renew to request a new lease. Use ipconfig /flushdns to clear the local DNS resolver cache. Use nslookup example.com to query DNS.'],['Command practice','ipconfig /release\nipconfig /renew\nipconfig /flushdns\nnslookup example.com']]},
{id:'lesson-wifi',phase:2,cat:'network',icon:'WF',title:'Wi-Fi Troubleshooting',time:'20 MIN',summary:'Diagnose connected-without-internet, weak signal, and authentication problems.',sections:[['Layered checks','Confirm airplane mode is off, signal is usable, the correct SSID is selected, and other devices are tested. Then inspect IP, gateway, and DNS information.'],['Isolation sequence','Ping loopback, local IP, gateway, a public IP, and finally a domain name. Each result identifies a different boundary: local TCP/IP, interface, LAN, internet route, or DNS.'],['Common causes','An APIPA address beginning 169.254 usually indicates no DHCP lease. A valid address with gateway failure suggests a local link, VLAN, access point, or gateway issue.'],['Command practice','ipconfig /all\nping 127.0.0.1\nping <gateway>\nping 8.8.8.8\nnslookup example.com']]},
{id:'lesson-users',phase:3,cat:'systems',icon:'AD',title:'Users and Active Directory',time:'25 MIN',summary:'Understand domains, organizational units, users, groups, and access basics.',sections:[['Directory concepts','Active Directory Domain Services centrally manages identities and computers. Organizational Units arrange objects. Security groups assign access more safely than granting permissions user by user.'],['Login triage','Confirm username format, domain, password state, network connection, time synchronization, account lockout, and whether another user can sign in.'],['Least privilege','Give only the permissions needed for the task. Use groups, separate administrative accounts, and documented approval for access changes.'],['Checkpoint','Create a diagram showing Domain → OU → Group → User and write one purpose for each.']]},
{id:'lesson-windows',phase:3,cat:'systems',icon:'WIN',title:'Windows Support Toolkit',time:'24 MIN',summary:'Use built-in Windows tools to investigate performance, startup, services, and errors.',sections:[['Core tools','Task Manager checks processes and performance. Resource Monitor adds detail. Services manages background services. Event Viewer records system and application events. Reliability Monitor provides a timeline.'],['System repair','Run system repair commands only with appropriate rights and after understanding impact. SFC checks protected system files; DISM can repair the Windows component store.'],['Commands','sfc /scannow\nDISM /Online /Cleanup-Image /RestoreHealth\nchkdsk /scan\nsysteminfo'],['Checkpoint','Open Reliability Monitor and identify the most recent critical event, without changing anything.']]},
{id:'lesson-printer',phase:4,cat:'support',icon:'PR',title:'Printer Troubleshooting',time:'18 MIN',summary:'Resolve offline printers, stuck queues, driver issues, and connectivity problems.',sections:[['Start with scope','Check whether one user or everyone is affected. Confirm power, display errors, paper, consumables, cable or network connection, and correct printer selection.'],['Queue and service','Check the print queue for paused or failed jobs. Confirm the printer is not set to offline. Restarting the Print Spooler can help, but consider its effect on all local print jobs.'],['Network printers','Verify the printer IP, ping it, open its web interface if permitted, confirm the correct TCP/IP port, and compare results from another workstation.'],['Checkpoint','Write a safe troubleshooting flow for one user who cannot print while everyone else can.']]},
{id:'lesson-m365',phase:4,cat:'support',icon:'365',title:'Microsoft 365 and Outlook',time:'22 MIN',summary:'Troubleshoot sign-in, sending, receiving, profiles, and service issues.',sections:[['First checks','Confirm internet access, account status, license, service health, correct time, and whether web access works. This separates account/service issues from the desktop application.'],['Outlook isolation','Check Work Offline, Outbox, mailbox quota, add-ins, credentials, data file state, and profile health. Safe Mode can help identify add-in problems.'],['Security','Never request a password. Verify identity using approved procedures before resets or MFA changes. Escalate suspected compromise immediately.'],['Checkpoint','Explain why testing Outlook on the web is a valuable isolation step.']]},
{id:'lesson-security',phase:4,cat:'support',icon:'SEC',title:'Support Security Essentials',time:'20 MIN',summary:'Protect identities, devices, data, and the organization during support work.',sections:[['Human layer','Phishing creates urgency and asks for credentials, payments, codes, or unsafe downloads. Verify unusual requests through a separate trusted channel.'],['Device layer','Use updates, approved endpoint protection, disk encryption, screen locks, backups, and least privilege. Do not disable security controls to make a symptom disappear.'],['Incident mindset','Preserve evidence, isolate only when authorized, record time and symptoms, and use the incident escalation process. Do not investigate beyond your authority.'],['Checkpoint','List three signs of phishing and the correct reporting action in your workplace.']]},
{id:'lesson-ticket',phase:4,cat:'support',icon:'TKT',title:'Tickets and Documentation',time:'16 MIN',summary:'Write support records that another technician can understand and continue.',sections:[['Good ticket structure','Record user/device, time, business impact, exact symptom, error text, scope, evidence, steps taken, results, resolution, verification, and follow-up.'],['Professional writing','Use facts instead of blame. “User reports error 0x…” is clearer than “User did it wrong.” Avoid passwords, sensitive personal data, and unnecessary confidential content.'],['Resolution note','A strong close note states the root cause when known, the change made, how success was verified, and whether prevention or monitoring is required.'],['Checkpoint','Rewrite this note: “Fixed computer. Working now.” Add evidence and verification.']]}
];
const labs=[
{id:'lab.hardware-triage',title:'No-Display Hardware Triage',level:'BEGINNER / 30 MIN',desc:'Use a safe external-to-internal inspection to isolate a simulated no-display failure.',steps:['Record the exact symptom, power state and recent changes.','Check monitor power, input, display cable and a known-good display.','Power down and disconnect equipment before internal inspection.','Use ESD precautions and verify RAM seating in the lab device.','Change one condition at a time and record each result.','Restore the working state and document final verification.'],verify:'Submit a check table showing observation, controlled test, result, likely cause and final successful display verification.'},
{id:'lab.windows-performance',title:'Windows Performance Evidence',level:'BEGINNER / 35 MIN',desc:'Use Task Manager and Reliability Monitor to investigate a controlled Windows slowdown.',steps:['Record startup time and the user-visible symptom.','Inspect CPU, memory, disk and startup impact in Task Manager.','Open Reliability Monitor and note the most relevant recent event.','Identify one safe reversible improvement.','Apply only the approved change and repeat the measurements.','Document before-and-after evidence and remaining risk.'],verify:'Provide the constrained resource or cause, supporting evidence, controlled action and measured verification.'},
{id:'lab-ip',title:'Build and Test a Small Network',level:'BEGINNER / 35 MIN',desc:'Configure two clients and a gateway in Packet Tracer, then verify connectivity.',steps:['Create one router, one switch, and two PCs.','Connect devices using the correct cables.','Use network 192.168.10.0/24. Set router LAN to 192.168.10.1.','Assign unique client IPs and use 192.168.10.1 as gateway.','Ping between clients and ping the gateway.','Record the addressing table and test results.'],verify:'Both PCs must ping each other and the router. Explain why duplicate IP addresses fail.'},
{id:'lab-dns',title:'Diagnose Internet vs DNS',level:'BEGINNER / 25 MIN',desc:'Use a controlled command sequence to identify where connectivity stops.',steps:['Open Command Prompt.','Run ipconfig /all and record IPv4, gateway, and DNS.','Ping 127.0.0.1, then your local IPv4, then the default gateway.','Ping 8.8.8.8, then run nslookup example.com.','For each result, write which layer it tests.','Do not change settings unless you understand the evidence.'],verify:'Produce a five-line result table and a conclusion: device, LAN, internet route, or DNS.'},
{id:'lab-ad',title:'Create an Active Directory User',level:'BEGINNER / 40 MIN',desc:'Practice structured identity administration in your Windows Server lab.',steps:['Open Active Directory Users and Computers.','Create a Training OU.','Create a security group named IT-Lab-Users.','Create a test user using a naming standard.','Add the user to the group.','On a domain client, verify sign-in and record the result.'],verify:'The user appears in the correct OU, has group membership, and can sign in to the domain client.'},
{id:'lab.m365-isolation',title:'Microsoft 365 Access Isolation',level:'BEGINNER / 30 MIN',desc:'Use a safe decision tree to separate service, account, license, MFA and Outlook profile causes.',steps:['Start with a scenario in which Outlook desktop cannot sign in.','Record service health, internet state, account state and license evidence.','Test approved web access without requesting or recording a password.','Compare the web and desktop results.','Choose the next safe client-side test based on evidence.','Write the resolution and verification note.'],verify:'The report must identify the failing boundary, protect credentials and include successful access verification.'},
{id:'lab-ticket',title:'Resolve and Document a Printer Issue',level:'BEGINNER / 30 MIN',desc:'Follow a support workflow and produce a professional resolution note.',steps:['Use the scenario: one user reports a network printer offline.','Write your scope and impact questions.','Create a check sequence from physical state through network and queue.','For each check, write the evidence you expect.','Assume the printer IP changed and correct the port in your simulated answer.','Write a complete ticket resolution note.'],verify:'The final note must include symptom, scope, evidence, root cause, fix, and user verification.'}
];
const quizQuestions=[
['Which service normally gives a client its IP address, subnet mask, gateway, and DNS?',['DNS','DHCP','HTTP','SMB'],1],
['A Windows client has address 169.254.20.8. What is the most likely meaning?',['It received a normal DHCP lease','It could not obtain a DHCP lease','DNS is working','The gateway is online'],1],
['Which command displays detailed Windows IP configuration?',['ipconfig /all','format','tasklist /delete','whois'],0],
['A domain name fails but pinging a public IP succeeds. Which area should you test next?',['RAM','DNS','Monitor cable','Printer spooler'],1],
['What should happen after implementing a fix?',['Close immediately','Verify full functionality and document','Delete the logs','Change another setting'],1],
['What is the safest way to assign shared folder access?',['Give every user admin rights','Use an approved security group','Share the password','Disable permissions'],1],
['Why test Outlook on the web?',['To replace Windows','To isolate account/service from desktop profile issues','To delete email','To reset the router'],1],
['Which tool shows Windows processes and resource use?',['Paint','Task Manager','Notepad','Calculator'],1],
['What is the best first response to a vague issue?',['Guess a fix','Collect symptom, scope, impact, and changes','Reinstall Windows','Replace the computer'],1],
['What belongs in a resolution note?',['A user password','Root cause, action, and verification','Blame','Unrelated personal data'],1]
];
const examQuestions=[
['A user says “Wi-Fi is connected but no sites open.” What is the best first technical check after confirming scope?',['Replace the laptop','Inspect IP, gateway, and DNS with ipconfig /all','Disable antivirus','Reset every network device'],1],
['The client has a valid IP but cannot ping its gateway. What boundary is failing?',['Local LAN path to the gateway','Only DNS','Email licensing','Printer queue'],0],
['One employee cannot sign in, but other domain users can. What should you examine first?',['Replace the domain controller','The user identity, password state, lockout, and username format','Rebuild the network','Disable MFA for everyone'],1],
['All users lose access to a shared service simultaneously. What does the scope suggest?',['Every keyboard failed','A shared service, network, or infrastructure issue','Each user forgot a password','A single local profile'],1],
['You receive a request to reset an executive password from an unknown caller. What is correct?',['Reset it quickly','Verify identity using the approved process before acting','Ask for the old password','Send a temporary password publicly'],1],
['After updating a printer TCP/IP port, what verifies the fix best?',['The settings window closed','A successful test page and user confirmation','The PC restarted','The ticket has a title'],1],
['An unknown attachment was opened and suspicious activity begins. What is the best response?',['Hide it','Follow incident procedure, preserve evidence, and escalate immediately','Delete all logs','Keep using the device normally'],1],
['Which ticket note is strongest?',['Fixed.','Restarted it.','Print failed for one user; old TCP/IP port pointed to 10.0.0.45. Updated approved port to 10.0.0.60; test page and user print succeeded.','User problem.'],2],
['A change may affect many employees. Before implementation you should consider:',['Only speed','Impact, approval, backup, and rollback','The wallpaper','Personal preference'],1],
['What makes troubleshooting professional?',['Many changes at once','Evidence, controlled tests, verification, and documentation','Confidence without checks','Always escalating immediately'],1]
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=load(),activeAssessment=null;
function defaults(){return{completed:[],quizBest:0,examBest:0,notes:'',lastVisit:'',missionProgress:{},authored:[],activeRecord:null,recordFilter:'all',activity:[]}}
const safeId=value=>typeof value==='string'&&/^[a-z0-9._-]{1,100}$/i.test(value)?value:'';
const safeText=(value,max=5000)=>typeof value==='string'?value.slice(0,max):'';
const safeContent=(value,max=5000)=>safeText(value,max).replace(/[<>]/g,'');
function normalizeState(raw){
  if(!raw||typeof raw!=='object'||Array.isArray(raw))return null;
  const clean=defaults(),allowedTypes=['topic','lesson','mission'],allowedStatuses=['draft','published'];
  clean.completed=Array.isArray(raw.completed)?raw.completed.map(safeId).filter(Boolean).slice(0,500):[];
  clean.quizBest=Math.max(0,Math.min(100,Number(raw.quizBest)||0));clean.examBest=Math.max(0,Math.min(100,Number(raw.examBest)||0));clean.notes=safeText(raw.notes,50000);clean.lastVisit=safeText(raw.lastVisit,40);clean.recordFilter=['all',...allowedTypes].includes(raw.recordFilter)?raw.recordFilter:'all';clean.activeRecord=safeId(raw.activeRecord)||null;
  if(raw.missionProgress&&typeof raw.missionProgress==='object'&&!Array.isArray(raw.missionProgress))Object.entries(raw.missionProgress).slice(0,500).forEach(([id,item])=>{const key=safeId(id);if(!key||!item||typeof item!=='object')return;clean.missionProgress[key]={steps:Array.isArray(item.steps)?item.steps.map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<20).slice(0,20):[],evidence:safeText(item.evidence,10000),verified:Boolean(item.verified)};});
  clean.authored=Array.isArray(raw.authored)?raw.authored.slice(0,200).map((record,index)=>{if(!record||typeof record!=='object')return null;const type=allowedTypes.includes(record.type)?record.type:'topic',id=safeId(record.id)||`local.${type}.imported-${index}`;return{id,type,academyId:safeId(record.academyId)||'academy.it-support',title:safeContent(record.title,80),summary:safeContent(record.summary,280),tags:Array.isArray(record.tags)?record.tags.map(x=>safeContent(x,40)).filter(Boolean).slice(0,20):[],topicIds:Array.isArray(record.topicIds)?record.topicIds.map(safeId).filter(Boolean).slice(0,50):[],status:allowedStatuses.includes(record.status)?record.status:'draft',blocks:Array.isArray(record.blocks)?record.blocks.map(x=>safeContent(typeof x==='string'?x:x?.content,2000)).filter(Boolean).slice(0,100):[],updatedAt:Number.isFinite(Date.parse(record.updatedAt))?record.updatedAt:new Date().toISOString()};}).filter(Boolean):[];
  return clean;
}
function load(){try{return normalizeState(JSON.parse(localStorage.getItem(storeKey)||'{}'))||defaults()}catch(e){return defaults()}}
function save(){localStorage.setItem(storeKey,JSON.stringify(state));updateProgress()}
async function digest(value){if(window.crypto&&window.crypto.subtle){const data=new TextEncoder().encode(value);const buf=await window.crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}let hash=2166136261;for(const char of String(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16).padStart(8,'0')}
function renderAll(){renderModules();renderAcademies();renderMissions();renderLibrary();renderRoadmap();renderLessons();renderLabs();renderAssessment('quiz');renderAssessment('exam');renderEditor();$('#notesText').value=state.notes;updateProgress();updateStreak()}
function isDone(id){return state.completed.includes(id)}
function toggleDone(id,force){const done=isDone(id);if(force===true&&!done)state.completed.push(id);else if(force===false&&done)state.completed=state.completed.filter(x=>x!==id);else if(force===undefined)state.completed=done?state.completed.filter(x=>x!==id):[...state.completed,id];save();renderModules();renderLessons();renderLabs();renderRoadmap();renderAcademies()}
function activeMissions(){return[...missions,...state.authored.filter(r=>r.type==='mission'&&r.status==='published').map(r=>{const blocks=(r.blocks||[]).map(b=>typeof b==='string'?b:b.content||'').filter(Boolean),steps=[...blocks.slice(0,4)];while(steps.length<4)steps.push(['Learn the linked knowledge','Practice the core workflow','Solve the learning scenario','Verify with written evidence'][steps.length]);return{id:r.id,academy:'Local Academy',title:r.title,objective:r.summary,topicIds:r.topicIds||[],steps,competency:r.summary,criteria:['Complete every mission step','Use the linked canonical topics','Record clear evidence and verification']}})]}
function publishedLessons(){return state.authored.filter(r=>r.type==='lesson'&&r.status==='published').map(r=>{const blocks=(r.blocks||[]).map(b=>typeof b==='string'?b:b.content||'').filter(Boolean);return{id:r.id,phase:1,cat:'authored',icon:'NEW',title:r.title,time:'SELF PACED',summary:r.summary,academyId:r.academyId||'academy.it-support',topicIds:r.topicIds||[],sections:blocks.map(block=>{const split=block.indexOf(':');return split>0?[block.slice(0,split).trim(),block.slice(split+1).trim()]:['Lesson Block',block]})}})}
function allLessons(){return[...lessons,...publishedLessons()]}
function lessonsForAcademy(academyId){const authored=publishedLessons().filter(x=>x.academyId===academyId);if(academyId==='academy.it-support')return[...lessons,...authored];if(academyId==='academy.networking')return[...lessons.filter(x=>['lesson-ip','lesson-dns','lesson-wifi'].includes(x.id)),...authored];return authored}
function renderCourseContent(academyId){const academy=academies.find(a=>a.id===academyId),items=lessonsForAcademy(academyId),panel=$('#courseContentPanel');if(!academy||!panel)return;panel.innerHTML=`<div class="section-title"><div><span>COURSE CONTENT</span><h2>${esc(academy.title)}</h2></div><b>${items.length} LESSONS</b></div>${items.length?`<div class="academy-lesson-grid">${items.map(item=>`<article class="academy-lesson ${isDone(item.id)?'completed':''}"><span>${esc(item.cat.toUpperCase())} / ${esc(item.time)}</span><h3>${esc(item.title)}</h3><p>${esc(item.summary)}</p><button data-open="${item.id}">${isDone(item.id)?'REVIEW LESSON':'OPEN LESSON'} →</button></article>`).join('')}</div>`:'<div class="course-empty"><h3>No Published Lessons Yet</h3><p>Open the Content Editor, create a Course Lesson, choose this academy and publish it</p><button data-view-jump="editor">OPEN CONTENT EDITOR →</button></div>'}`}
function updateProgress(){const courseLessons=allLessons(),total=courseLessons.length+labs.length,completed=[...courseLessons,...labs].filter(x=>isDone(x.id)).length,p=Math.round(completed/total*100),all=activeMissions(),verified=all.filter(m=>missionDone(m.id)).length,readiness=Math.round(verified/all.length*100);$('#overallPercent').textContent=readiness+'%';$('#completedLabel').textContent=`${verified} of ${all.length} competencies`;$('#progressRing').style.setProperty('--progress',readiness+'%');$('#statProgress').textContent=p+'%';$('#statLabs').textContent=`${verified} / ${all.length}`;$('#statQuiz').textContent=readiness+'%';const next=all.find(m=>!missionDone(m.id));if($('#nextActionCopy'))$('#nextActionCopy').textContent=next?`${next.title}: ${next.objective}`:'All Phase 1 missions are verified. Review your evidence or create the next mission.'}
function renderModules(){const picks=[lessons[0],lessons[3],lessons[6],lessons[8]];$('#dashboardModules').innerHTML=picks.map((x,i)=>`<article class="module-card ${isDone(x.id)?'completed':''}"><span>MODULE ${String(i+1).padStart(2,'0')} / ${x.cat.toUpperCase()}</span><h3>${x.title}</h3><p>${x.summary}</p><button data-open="${x.id}" aria-label="Open ${x.title}">→</button></article>`).join('')}
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderAcademies(){const authored=publishedLessons();$('#academyCatalog').innerHTML=academies.map((a,i)=>{const lessonCount=lessonsForAcademy(a.id).length;return`<article class="course-card ${a.status==='ACTIVE'?'available':''}"><div class="course-top"><span>${a.status}</span><b>${String(i+1).padStart(2,'0')}</b></div><h2>${a.title}</h2><p>${a.summary}</p><div class="course-stats"><span>${a.missions.length} MISSIONS</span><span>${lessonCount} LESSONS</span><span>${a.topics.length} SHARED TOPICS</span></div><button data-academy-content="${a.id}">${lessonCount?'OPEN COURSE CONTENT':'VIEW COURSE'} →</button></article>`}).join('');renderCourseContent('academy.it-support')}
function missionState(id){return Object.assign({steps:[],evidence:'',verified:false},state.missionProgress[id]||{})}
function missionDone(id){const m=activeMissions().find(x=>x.id===id),p=missionState(id);return Boolean(m&&p.verified&&p.evidence.trim().length>=20&&p.steps.length===m.steps.length)}
function renderMissions(){const all=activeMissions();$('#missionList').innerHTML=all.map((m,i)=>{const p=missionState(m.id),done=missionDone(m.id),lab=labs.find(x=>x.id===m.labId),linked=allTopicOptions().filter(t=>(m.topicIds||[]).includes(t.id));return`<article class="mission-card ${done?'verified':''}"><div class="mission-head"><div><span>${m.academy} / MISSION ${String(i+1).padStart(2,'0')}</span><h2>${m.title}</h2><p>${m.objective}</p></div><b>${done?'VERIFIED':Math.round(p.steps.length/m.steps.length*100)+'%'}</b></div><div class="mission-links"><div><small>CANONICAL TOPICS</small>${linked.map(t=>`<button data-library-topic="${t.id}">${t.title}</button>`).join('')}</div>${lab?`<button class="mission-lab" data-open="${lab.id}">OPEN PRACTICAL LAB →</button>`:''}</div><div class="mission-steps">${m.steps.map((s,j)=>`<label><input type="checkbox" data-mission-step="${m.id}" data-step="${j}" ${p.steps.includes(j)?'checked':''}><span><small>${['LEARN','PRACTICE','SOLVE','VERIFY'][j]}</small>${s}</span></label>`).join('')}</div><div class="mission-criteria"><small>VERIFICATION CRITERIA</small><ul>${(m.criteria||[]).map(c=>`<li>${c}</li>`).join('')}</ul></div><label class="evidence-field">EVIDENCE<textarea data-mission-evidence="${m.id}" placeholder="Record what you did, the result and how you verified it…">${esc(p.evidence)}</textarea></label><div class="mission-foot"><span>COMPETENCY / ${m.competency}</span><button data-verify-mission="${m.id}" ${p.steps.length!==m.steps.length||p.evidence.trim().length<20?'disabled':''}>${done?'✓ COMPETENCY EARNED':'VERIFY MISSION'}</button></div></article>`}).join('')}
function renderLibrary(query=''){const authored=state.authored.filter(x=>x.type==='topic'&&x.status==='published').map(x=>({id:x.id,title:x.title,summary:x.summary,tags:x.tags||[],usedBy:['Local Academy']})),all=[...topics,...authored],q=query.trim().toLowerCase(),filtered=all.filter(t=>`${t.title} ${t.summary} ${(t.tags||[]).join(' ')}`.toLowerCase().includes(q));$('#libraryCount').textContent=`${filtered.length} OF ${all.length} TOPICS`;$('#libraryGrid').innerHTML=filtered.length?filtered.map(t=>`<article class="library-card"><span>${t.id}</span><h2>${esc(t.title)}</h2><p>${esc(t.summary)}</p><div>${(t.tags||[]).map(tag=>`<b>${esc(tag)}</b>`).join('')}</div><small>USED BY / ${(t.usedBy||['Local Academy']).map(esc).join(' · ')}</small></article>`).join(''):'<div class="search-empty">No canonical topic matches your search.</div>'}
function emptyRecord(type='topic'){return{id:`local.${type}.${Date.now()}`,type,academyId:'academy.it-support',title:'',summary:'',tags:[],topicIds:[],status:'draft',blocks:[],updatedAt:new Date().toISOString()}}
function currentRecord(){return state.authored.find(x=>x.id===state.activeRecord)||null}
function allTopicOptions(){return[...topics,...state.authored.filter(x=>x.type==='topic').map(x=>({id:x.id,title:x.title||'Untitled local topic'}))]}
function renderEditor(){const filtered=state.authored.filter(r=>state.recordFilter==='all'||r.type===state.recordFilter);$$('[data-record-filter]').forEach(b=>b.classList.toggle('active',b.dataset.recordFilter===state.recordFilter));$('#recordList').innerHTML=filtered.length?filtered.map(r=>`<article class="record-row ${r.id===state.activeRecord?'active':''}"><button type="button" data-edit-record="${r.id}"><span>${r.type.toUpperCase()} / ${r.status.toUpperCase()}</span><b>${esc(r.title||'Untitled record')}</b><small>EDITED ${new Date(r.updatedAt).toLocaleDateString()}</small></button><button type="button" data-quick-delete="${r.id}" aria-label="Delete ${esc(r.title||'untitled record')}">×</button></article>`).join(''):'<p class="editor-empty">No matching local records. Create a topic, course lesson or mission above.</p>';const options=allTopicOptions();$('#recordTopics').innerHTML=options.map(t=>`<option value="${t.id}">${esc(t.title)} — ${t.id}</option>`).join('');const r=currentRecord();$('#duplicateRecord').disabled=!r;$('#deleteRecord').disabled=!r;if(!r){$('#editorForm').reset();$('#recordType').value='topic';$('#editorState').textContent='NO RECORD';$('#editorSaveStatus').textContent='Choose a topic, course lesson or mission';$('#academyField').hidden=true;$('#topicLinksField').hidden=true;$('#livePreview').innerHTML='<p class="preview-empty">Create or select a record to begin.</p>';$('#validationPanel').classList.remove('valid');$('#validationPanel').textContent='Create or select a record to begin.';return}r.tags=r.tags||[];r.topicIds=r.topicIds||[];r.blocks=(r.blocks||[]).map(b=>typeof b==='string'?b:b.content||'');$('#recordType').value=r.type;$('#recordAcademy').value=r.academyId||'academy.it-support';$('#recordTitle').value=r.title;$('#recordSummary').value=r.summary;$('#recordTags').value=r.tags.join(', ');$('#recordStatus').value=r.status;$('#recordBlocks').value=r.blocks.join('\n');[...$('#recordTopics').options].forEach(o=>o.selected=r.topicIds.includes(o.value));$('#academyField').hidden=r.type==='topic';$('#topicLinksField').hidden=r.type==='topic';$('#editorState').textContent=`EDITING ${r.type.toUpperCase()}`;$('#editorSaveStatus').textContent='Saved locally';updateEditorPreview();validateEditor()}
function collectEditor(){const type=$('#recordType').value;return{id:state.activeRecord||`local.${type}.${Date.now()}`,type,academyId:$('#recordAcademy').value,title:safeContent($('#recordTitle').value.trim(),80),summary:safeContent($('#recordSummary').value.trim(),280),tags:$('#recordTags').value.split(',').map(x=>safeContent(x.trim(),40)).filter(Boolean),topicIds:[...$('#recordTopics').selectedOptions].map(o=>safeId(o.value)).filter(Boolean),status:$('#recordStatus').value,blocks:$('#recordBlocks').value.split('\n').map(x=>safeContent(x.trim(),2000)).filter(Boolean),updatedAt:new Date().toISOString()}}
function editorErrors(r){const errors=[];if(r.title.length<4)errors.push('Add a title with at least 4 characters.');if(r.summary.length<20)errors.push('Add a useful summary with at least 20 characters.');if(!r.blocks.length)errors.push('Add at least one content block.');if(['lesson','mission'].includes(r.type)&&!r.topicIds.length)errors.push(`Link the ${r.type} to at least one Knowledge Library topic.`);if(r.type==='lesson'&&!r.academyId)errors.push('Choose an academy for the course lesson.');if(r.status==='published'&&r.type==='topic'&&r.blocks.length<3)errors.push('Published topics need at least three blocks.');if(r.status==='published'&&r.type==='lesson'&&r.blocks.length<3)errors.push('Published course lessons need at least three structured blocks.');if(r.status==='published'&&r.type==='mission'&&r.blocks.length<4)errors.push('Published missions need four blocks: Learn, Practice, Solve and Verify.');return errors}
function validateEditor(){if(!currentRecord()&&!$('#recordTitle').value)return[];const r=collectEditor(),errors=editorErrors(r),panel=$('#validationPanel');panel.classList.toggle('valid',!errors.length);panel.textContent=errors.length?errors.join(' '):'Ready to save. All required structure and topic links are valid.';return errors}
function updateEditorPreview(){const r=collectEditor(),linked=allTopicOptions().filter(t=>r.topicIds.includes(t.id)),academy=academies.find(a=>a.id===r.academyId);$('#academyField').hidden=r.type==='topic';$('#topicLinksField').hidden=r.type==='topic';$('#livePreview').innerHTML=`<span>${r.type.toUpperCase()} / ${r.status.toUpperCase()}</span><h2>${esc(r.title||'Untitled record')}</h2>${r.type!=='topic'&&academy?`<small class="preview-academy">${esc(academy.title)}</small>`:''}<p>${esc(r.summary||'Your learner-facing summary will appear here.')}</p>${linked.length?`<div class="preview-links"><small>LINKED KNOWLEDGE</small>${linked.map(t=>`<b>${esc(t.title)}</b>`).join('')}</div>`:''}${r.blocks.map((b,i)=>`<section><small>BLOCK ${String(i+1).padStart(2,'0')}</small><p>${esc(b)}</p></section>`).join('')}`;validateEditor()}
function renderRoadmap(){const names=['IT Foundations','Networking Core','Windows and Identity','Service Desk Readiness'],courseLessons=allLessons();$('#roadmapList').innerHTML=names.map((name,i)=>{const items=courseLessons.filter(x=>x.phase===i+1);return`<article class="roadmap-phase"><div class="phase-number">PHASE ${String(i+1).padStart(2,'0')}</div><div class="phase-content"><h2>${name}</h2><p>${items.filter(x=>isDone(x.id)).length} of ${items.length} lessons completed</p><div class="phase-items">${items.map(x=>`<button data-open="${x.id}">${isDone(x.id)?'✓ ':''}${x.title}</button>`).join('')}</div></div></article>`}).join('')}
function renderLessons(filter='all',query=''){const list=allLessons().filter(x=>(filter==='all'||x.cat===filter)&&(`${x.title} ${x.summary} ${x.cat}`.toLowerCase().includes(query.toLowerCase())));$('#lessonGrid').innerHTML=list.length?list.map(x=>`<article class="lesson-card ${isDone(x.id)?'completed':''}"><div class="lesson-icon">${x.icon}</div><h2>${x.title}</h2><p>${x.summary}</p><div class="lesson-meta"><span>${x.cat.toUpperCase()}</span><span>${x.time}</span></div><button data-open="${x.id}" aria-label="Open ${x.title}"></button></article>`).join(''):'<div class="search-empty">No learning content matches your search.</div>'}
function renderLabs(query=''){const list=labs.filter(x=>(`${x.title} ${x.desc}`.toLowerCase().includes(query.toLowerCase())));$('#labList').innerHTML=list.length?list.map((x,i)=>`<article class="lab-card ${isDone(x.id)?'completed':''}"><div class="lab-index">${String(i+1).padStart(2,'0')}</div><div class="lab-info"><span>${x.level}</span><h2>${x.title}</h2><p>${x.desc}</p></div><div class="lab-actions"><button data-open="${x.id}">OPEN LAB</button><button class="complete" data-complete="${x.id}">${isDone(x.id)?'✓ COMPLETED':'MARK COMPLETE'}</button></div></article>`).join(''):'<div class="search-empty">No labs match your search.</div>'}
function openContent(id){const item=[...allLessons(),...labs].find(x=>x.id===id);if(!item)return;let html;if(item.sections){html=`<div class="dialog-content"><p class="kicker">LESSON / ${item.cat.toUpperCase()} / ${item.time}</p><h1>${item.title}</h1><p class="summary">${item.summary}</p>${item.sections.map(s=>`<section class="lesson-section"><h2>${s[0]}</h2>${s[0].toLowerCase().includes('command')?`<div class="command-box">${s[1]}</div>`:`<p>${s[1]}</p>`}</section>`).join('')}<div class="dialog-footer"><span class="kicker">LEARN → PRACTICE → VERIFY</span><button data-dialog-complete="${item.id}" class="${isDone(item.id)?'done':''}">${isDone(item.id)?'✓ LESSON COMPLETED':'MARK LESSON COMPLETE'}</button></div></div>`}else{html=`<div class="dialog-content"><p class="kicker">PRACTICE LAB / ${item.level}</p><h1>${item.title}</h1><p class="summary">${item.desc}</p><section class="lesson-section"><h2>Lab procedure</h2><ol>${item.steps.map(s=>`<li>${s}</li>`).join('')}</ol></section><section class="lesson-section"><h2>Verification standard</h2><p>${item.verify}</p></section><div class="dialog-footer"><span class="kicker">DO NOT GUESS — RECORD EVIDENCE</span><button data-dialog-complete="${item.id}" class="${isDone(item.id)?'done':''}">${isDone(item.id)?'✓ LAB COMPLETED':'MARK LAB COMPLETE'}</button></div></div>`}$('#dialogBody').innerHTML=html;$('#contentDialog').showModal()}
function renderAssessment(type){const area=$(`#${type}Area`),best=type==='quiz'?state.quizBest:state.examBest,count=(type==='quiz'?quizQuestions:examQuestions).length;area.innerHTML=`<div class="assessment-start"><strong>${best?best+'%':count}</strong><h2>${best?'Best score':'Questions ready'}</h2><p>${type==='quiz'?'A focused course knowledge check.':'A scenario-based final assessment covering safe support decisions.'}<br>Your best result is saved on this device.</p><button class="start-btn" data-start="${type}">${best?'TRY AGAIN':'START '+type.toUpperCase()} →</button></div>`}
function startAssessment(type){activeAssessment={type,index:0,answers:[]};showQuestion()}
function showQuestion(){const a=activeAssessment,qs=a.type==='quiz'?quizQuestions:examQuestions,q=qs[a.index],area=$(`#${a.type}Area`);area.innerHTML=`<div class="question"><div class="question-head"><span>${a.type.toUpperCase()} / QUESTION ${a.index+1}</span><span>${a.index+1} OF ${qs.length}</span></div><h2>${q[0]}</h2><div class="answers">${q[1].map((v,i)=>`<button class="answer" data-answer="${i}"><b>${String.fromCharCode(65+i)}.</b> ${v}</button>`).join('')}</div><div class="question-actions"><button class="next-btn" disabled>${a.index===qs.length-1?'SUBMIT ASSESSMENT':'NEXT QUESTION →'}</button></div></div>`}
function finishAssessment(){const a=activeAssessment,qs=a.type==='quiz'?quizQuestions:examQuestions,correct=a.answers.filter((v,i)=>v===qs[i][2]).length,score=Math.round(correct/qs.length*100),pass=score>=80;if(a.type==='quiz')state.quizBest=Math.max(state.quizBest,score);else state.examBest=Math.max(state.examBest,score);save();const area=$(`#${a.type}Area`);area.innerHTML=`<div class="result"><p class="kicker">${pass?'ASSESSMENT PASSED':'MORE PRACTICE NEEDED'}</p><strong>${score}%</strong><h2>${correct} of ${qs.length} correct</h2><p>${pass?'Strong work. Review your notes and continue practicing the workflow in real labs.':'Review the relevant lessons, repeat the practical labs, and try again. Accuracy matters more than speed.'}</p><button data-start="${a.type}">RETAKE ${a.type.toUpperCase()}</button></div>`;activeAssessment=null;updateProgress()}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('#academyNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function updateStreak(){const today=new Date().toISOString().slice(0,10),last=state.lastVisit;state.lastVisit=today;save();$('#statStreak').textContent=last===today?'1 DAY':'1 DAY'}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)openContent(open.dataset.open);const jump=e.target.closest('[data-view-jump]');if(jump)showView(jump.dataset.viewJump);const nav=e.target.closest('#academyNav [data-view]');if(nav)showView(nav.dataset.view);const comp=e.target.closest('[data-complete]');if(comp)toggleDone(comp.dataset.complete);const dialogComp=e.target.closest('[data-dialog-complete]');if(dialogComp){toggleDone(dialogComp.dataset.dialogComplete);openContent(dialogComp.dataset.dialogComplete)}const start=e.target.closest('[data-start]');if(start)startAssessment(start.dataset.start);const ans=e.target.closest('[data-answer]');if(ans&&activeAssessment){$$('.answer').forEach(x=>x.classList.remove('selected'));ans.classList.add('selected');activeAssessment.answers[activeAssessment.index]=Number(ans.dataset.answer);$('.next-btn').disabled=false}const next=e.target.closest('.next-btn');if(next&&activeAssessment){const qs=activeAssessment.type==='quiz'?quizQuestions:examQuestions;if(activeAssessment.index<qs.length-1){activeAssessment.index++;showQuestion()}else finishAssessment()}});
$('#dialogClose').onclick=()=>$('#contentDialog').close();$('#contentDialog').addEventListener('click',e=>{if(e.target===$('#contentDialog'))$('#contentDialog').close()});$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');
$('#themeButton').onclick=()=>{const t=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=t;localStorage.setItem('portfolio-theme',t);$('#themeButton').textContent=t==='light'?'☀':'☾'};
document.addEventListener('change',e=>{const step=e.target.closest('[data-mission-step]');if(step){const id=step.dataset.missionStep,index=Number(step.dataset.step),p=missionState(id);p.steps=step.checked?[...new Set([...p.steps,index])]:p.steps.filter(x=>x!==index);if(!step.checked)p.verified=false;state.missionProgress[id]=p;save();renderMissions()}const evidence=e.target.closest('[data-mission-evidence]');if(evidence){const p=missionState(evidence.dataset.missionEvidence);p.evidence=evidence.value;if(p.evidence.trim().length<20)p.verified=false;state.missionProgress[evidence.dataset.missionEvidence]=p;save();renderMissions()}});
document.addEventListener('input',e=>{const evidence=e.target.closest('[data-mission-evidence]');if(!evidence)return;const id=evidence.dataset.missionEvidence,p=missionState(id),m=activeMissions().find(x=>x.id===id);p.evidence=evidence.value;if(p.evidence.trim().length<20)p.verified=false;state.missionProgress[id]=p;localStorage.setItem(storeKey,JSON.stringify(state));const card=evidence.closest('.mission-card'),button=card&&card.querySelector('[data-verify-mission]');if(button&&m)button.disabled=p.steps.length!==m.steps.length||p.evidence.trim().length<20});
function deleteAuthored(id){const record=state.authored.find(x=>x.id===id);if(!record)return;if(!confirm(`Delete “${record.title||'Untitled record'}”? This removes the local record from this device.`))return;state.authored=state.authored.filter(x=>x.id!==id);state.authored.forEach(x=>{if(x.topicIds)x.topicIds=x.topicIds.filter(topicId=>topicId!==id)});if(state.activeRecord===id)state.activeRecord=null;save();renderEditor();renderLibrary($('#librarySearch').value);renderMissions();renderAcademies();renderRoadmap();renderLessons();updateProgress()}
document.addEventListener('click',e=>{const verify=e.target.closest('[data-verify-mission]');if(verify){const id=verify.dataset.verifyMission,p=missionState(id),m=activeMissions().find(x=>x.id===id);if(m&&p.steps.length===m.steps.length&&p.evidence.trim().length>=20){p.verified=true;state.missionProgress[id]=p;state.activity.unshift({type:'competency',subjectId:id,at:new Date().toISOString()});save();renderMissions()}}const edit=e.target.closest('[data-edit-record]');if(edit){state.activeRecord=edit.dataset.editRecord;save();renderEditor()}const quickDelete=e.target.closest('[data-quick-delete]');if(quickDelete)deleteAuthored(quickDelete.dataset.quickDelete);const topic=e.target.closest('[data-library-topic]');if(topic){showView('library');const match=allTopicOptions().find(t=>t.id===topic.dataset.libraryTopic);$('#librarySearch').value=match?.title||'';renderLibrary($('#librarySearch').value)}const addBlock=e.target.closest('[data-add-block]');if(addBlock){const area=$('#recordBlocks'),prefix=addBlock.dataset.addBlock,current=area.value.trim();area.value=(current?current+'\n':'')+`${prefix}: `;area.focus();area.setSelectionRange(area.value.length,area.value.length);updateEditorPreview();$('#editorSaveStatus').textContent='Unsaved changes'}});
$('#librarySearch').addEventListener('input',e=>renderLibrary(e.target.value));
function createRecord(type){const r=emptyRecord(type);state.authored.unshift(r);state.activeRecord=r.id;state.recordFilter='all';save();renderEditor();$('#recordTitle').focus()}
$('#newTopic').onclick=()=>createRecord('topic');$('#newLesson').onclick=()=>createRecord('lesson');$('#newMission').onclick=()=>createRecord('mission');
$$('[data-record-filter]').forEach(button=>button.onclick=()=>{state.recordFilter=button.dataset.recordFilter;save();renderEditor()});
['recordType','recordAcademy','recordTitle','recordSummary','recordTags','recordStatus','recordBlocks','recordTopics'].forEach(id=>$('#'+id).addEventListener('input',()=>{updateEditorPreview();$('#editorSaveStatus').textContent='Unsaved changes'}));
$('#recordType').addEventListener('change',()=>{const r=currentRecord();if(r)r.type=$('#recordType').value;updateEditorPreview()});
$('#editorForm').addEventListener('submit',e=>{e.preventDefault();const r=collectEditor(),errors=editorErrors(r);if(errors.length){validateEditor();return}const index=state.authored.findIndex(x=>x.id===r.id);if(index>=0)state.authored[index]=r;else state.authored.unshift(r);state.activeRecord=r.id;state.activity.unshift({type:'content-save',subjectId:r.id,at:new Date().toISOString()});save();$('#editorSaveStatus').textContent='Saved locally';renderEditor();renderLibrary($('#librarySearch').value);renderMissions();renderAcademies();renderRoadmap();renderLessons();updateProgress()});
$('#previewRecord').onclick=()=>{$('#livePreview').scrollIntoView({behavior:'smooth',block:'center'})};
$('#duplicateRecord').onclick=()=>{const source=currentRecord();if(!source)return;const copy=JSON.parse(JSON.stringify(source));copy.id=`local.${source.type}.${Date.now()}`;copy.title=`${source.title} (Copy)`;copy.status='draft';copy.updatedAt=new Date().toISOString();state.authored.unshift(copy);state.activeRecord=copy.id;save();renderEditor()};
$('#deleteRecord').onclick=()=>{if(state.activeRecord)deleteAuthored(state.activeRecord)};
$$('#lessonFilters button').forEach(b=>b.onclick=()=>{$$('#lessonFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLessons(b.dataset.filter,$('#searchInput').value)});
$('#searchInput').addEventListener('input',e=>{showView('library');$('#librarySearch').value=e.target.value;renderLibrary(e.target.value)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape')$('#sidebar').classList.remove('open')});
let noteTimer;$('#notesText').addEventListener('input',e=>{clearTimeout(noteTimer);$('#notesStatus').textContent='Saving…';noteTimer=setTimeout(()=>{state.notes=e.target.value;save();$('#notesStatus').textContent='Saved automatically'},400)});$('#exportNotes').onclick=()=>{const blob=new Blob([`MUHAMMAD ARSALAN — IT SUPPORT ACADEMY NOTES\nExported: ${new Date().toLocaleString()}\n\n${state.notes}`],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Muhammad-Arsalan-Academy-Notes.txt';a.click();URL.revokeObjectURL(a.href)};
function downloadFile(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),100)}
async function checksum(payload){return'sha256:'+await digest(JSON.stringify(payload))}
async function backupEnvelope(sourceState=state){const payload={state:sourceState};return{format:'academy-os-backup',formatVersion:1,schemaVersion:'1.0.0',productVersion:'2.0.0',exportedAt:new Date().toISOString(),owner:'Muhammad Arsalan',payload,checksum:await checksum(payload)}}
$('#exportProgress').onclick=async()=>downloadFile('Muhammad-Arsalan-Academy-OS-Backup.json',JSON.stringify(await backupEnvelope(),null,2),'application/json');
$('#importProgress').addEventListener('change',event=>{const file=event.target.files&&event.target.files[0];if(!file)return;if(file.size>2_000_000){alert('Backup is larger than the 2 MB safety limit.');event.target.value='';return}const reader=new FileReader();reader.onload=async()=>{try{const data=JSON.parse(reader.result),modern=data&&data.format==='academy-os-backup',incoming=modern?data.payload&&data.payload.state:data&&data.state;if(modern&&data.checksum!==await checksum(data.payload))throw new Error('Checksum mismatch');const normalized=normalizeState(incoming);if(!normalized)throw new Error('Invalid backup');const summary=`${normalized.completed.length} completed activities, ${Object.keys(normalized.missionProgress).length} missions and ${normalized.authored.length} authored records`;if(!confirm(`Validated backup from ${data.exportedAt?new Date(data.exportedAt).toLocaleString():'an earlier version'} (${summary}). Restore it now? Current local data will be replaced.`))return;downloadFile('Academy-OS-Pre-Restore-Backup.json',JSON.stringify(await backupEnvelope(),null,2),'application/json');state=normalized;save();renderAll();alert('Academy OS backup restored successfully.')}catch(error){alert(error.message==='Checksum mismatch'?'Backup checksum failed. The file may be damaged or changed.':'This file is not a valid Academy OS backup.')}event.target.value=''};reader.readAsText(file)});
$('#resetProgress').onclick=()=>{if(!confirm('Reset all Academy OS progress, missions, authored content, scores and notes? Export a backup first if you want to keep them.'))return;state=defaults();save();renderAll();showView('dashboard')};
document.addEventListener('click',e=>{const button=e.target.closest('[data-academy-content]');if(!button)return;renderCourseContent(button.dataset.academyContent);$('#courseContentPanel').scrollIntoView({behavior:'smooth',block:'start'})});
renderAll();
})();
