(()=>{'use strict';
const PASS_HASH='e7e12f05648dac4d8674fa920a4dd8cd1c0fdf847f12e2176106d29b8f81df84'; // Default key: ARSALAN2026
const storeKey='ma-academy-v1';
const lessons=[
{id:'lesson-hardware',phase:1,cat:'foundation',icon:'HW',title:'Computer Hardware Essentials',time:'18 MIN',summary:'Understand the components inside a computer and recognize common hardware symptoms.',sections:[['What you need to know','The CPU processes instructions, RAM holds active working data, storage keeps files, the motherboard connects components, and the power supply provides stable electrical power. A technician identifies the failing layer before replacing parts.'],['Real example','A computer that powers on but shows no display may have a loose display cable, wrong monitor input, RAM seating problem, or graphics failure. Start with external checks before opening the device.'],['Safe workflow','Power down, disconnect power, use ESD precautions, document cable locations, and change only one thing at a time. Never open equipment when doing so violates a warranty or workplace policy.'],['Checkpoint','Explain the difference between RAM and storage. Then identify three reasons a computer may have no display.']]},
{id:'lesson-os',phase:1,cat:'foundation',icon:'OS',title:'Operating System Fundamentals',time:'20 MIN',summary:'Learn how Windows manages hardware, applications, files, users, and services.',sections:[['Core idea','The operating system connects users and applications to hardware. Windows services run background functions, Device Manager shows hardware state, Task Manager shows resource use, and Event Viewer records important events.'],['Useful tools','Open Task Manager with Ctrl + Shift + Esc. Open Run with Win + R. Use msinfo32 for system information, devmgmt.msc for Device Manager, and eventvwr.msc for Event Viewer.'],['Real example','If an application freezes, check Task Manager before restarting the entire computer. Observe CPU, memory, disk, and the application status.'],['Checkpoint','Open Task Manager and identify the three processes currently using the most memory.']]},
{id:'lesson-method',phase:1,cat:'support',icon:'TS',title:'Troubleshooting Method',time:'15 MIN',summary:'Use a repeatable evidence-based process instead of guessing.',sections:[['Six-step process','1. Identify the problem. 2. Establish a probable cause. 3. Test the cause. 4. Plan and implement the fix. 5. Verify full functionality. 6. Document findings and actions.'],['Question quality','Ask what changed, when it started, who is affected, what error appears, what still works, and what has already been tried. These questions narrow the scope.'],['Change control','Before a risky change, consider impact, approval, rollback, and backup. A technically possible fix is not always an operationally safe fix.'],['Checkpoint','Write five questions you would ask a user who says, “The internet is broken.”']]},
{id:'lesson-ip',phase:2,cat:'network',icon:'IP',title:'IP Addressing and TCP/IP',time:'25 MIN',summary:'Understand IP addresses, subnet masks, gateways, ports, TCP, and UDP.',sections:[['Addressing','An IPv4 address identifies an interface. The subnet mask identifies the local network portion. The default gateway routes traffic to other networks. A DNS server translates names into IP addresses.'],['TCP and UDP','TCP confirms delivery and ordering, making it suitable for web sessions, email, and file transfer. UDP has lower overhead and is common for voice, video, and DNS queries.'],['Commands','Use ipconfig /all to inspect configuration. Use ping to test reachability. Use tracert to view the path. Use netstat -ano to inspect connections and listening ports.'],['Command practice','ipconfig /all\nping 127.0.0.1\nping <default-gateway>\ntracert 8.8.8.8']]},
{id:'lesson-dns',phase:2,cat:'network',icon:'DNS',title:'DNS and DHCP',time:'22 MIN',summary:'Learn how devices receive configurations and resolve human-readable names.',sections:[['DHCP','DHCP normally provides an IP address, subnet mask, gateway, and DNS server. The DORA sequence is Discover, Offer, Request, Acknowledge.'],['DNS','DNS resolution commonly checks browser/OS cache, the hosts file, and configured DNS resolvers. A website may fail by name while its server IP remains reachable.'],['Commands','Use ipconfig /release and ipconfig /renew to request a new lease. Use ipconfig /flushdns to clear the local DNS resolver cache. Use nslookup example.com to query DNS.'],['Command practice','ipconfig /release\nipconfig /renew\nipconfig /flushdns\nnslookup example.com']]},
{id:'lesson-wifi',phase:2,cat:'network',icon:'WF',title:'Wi-Fi Troubleshooting',time:'20 MIN',summary:'Diagnose connected-without-internet, weak signal, and authentication problems.',sections:[['Layered checks','Confirm airplane mode is off, signal is usable, the correct SSID is selected, and other devices are tested. Then inspect IP, gateway, and DNS information.'],['Isolation sequence','Ping loopback, local IP, gateway, a public IP, and finally a domain name. Each result identifies a different boundary: local TCP/IP, interface, LAN, internet route, or DNS.'],['Common causes','An APIPA address beginning 169.254 usually indicates no DHCP lease. A valid address with gateway failure suggests a local link, VLAN, access point, or gateway issue.'],['Command practice','ipconfig /all\nping 127.0.0.1\nping <gateway>\nping 8.8.8.8\nnslookup example.com']]},
{id:'lesson-users',phase:3,cat:'systems',icon:'AD',title:'Users and Active Directory',time:'25 MIN',summary:'Understand domains, organizational units, users, groups, and access basics.',sections:[['Directory concepts','Active Directory Domain Services centrally manages identities and computers. Organizational Units arrange objects. Security groups assign access more safely than granting permissions user by user.'],['Login triage','Confirm username format, domain, password state, network connection, time synchronization, account lockout, and whether another user can sign in.'],['Least privilege','Give only the permissions needed for the task. Use groups, separate administrative accounts, and documented approval for access changes.'],['Checkpoint','Create a diagram showing Domain → OU → Group → User and write one purpose for each.']]},
{id:'lesson-windows',phase:3,cat:'systems',icon:'WIN',title:'Windows Support Toolkit',time:'24 MIN',summary:'Use built-in Windows tools to investigate performance, startup, services, and errors.',sections:[['Core tools','Task Manager checks processes and performance. Resource Monitor adds detail. Services manages background services. Event Viewer records system and application events. Reliability Monitor provides a timeline.'],['System repair','Run system repair commands only with appropriate rights and after understanding impact. SFC checks protected system files; DISM can repair the Windows component store.'],['Commands','sfc /scannow\nDISM /Online /Cleanup-Image /RestoreHealth\nchkdsk /scan\nsysteminfo'],['Checkpoint','Open Reliability Monitor and identify the most recent critical event, without changing anything.']]},
{id:'lesson-printer',phase:4,cat:'support',icon:'PR',title:'Printer Troubleshooting',time:'18 MIN',summary:'Resolve offline printers, stuck queues, driver issues, and connectivity problems.',sections:[['Start with scope','Check whether one user or everyone is affected. Confirm power, display errors, paper, consumables, cable or network connection, and correct printer selection.'],['Queue and service','Check the print queue for paused or failed jobs. Confirm the printer is not set to offline. Restarting the Print Spooler can help, but consider its effect on all local print jobs.'],['Network printers','Verify the printer IP, ping it, open its web interface if permitted, confirm the correct TCP/IP port, and compare results from another workstation.'],['Checkpoint','Write a safe troubleshooting flow for one user who cannot print while everyone else can.']]},
{id:'lesson-m365',phase:4,cat:'support',icon:'365',title:'Microsoft 365 and Outlook',time:'22 MIN',summary:'Troubleshoot sign-in, sending, receiving, profiles, and service issues.',sections:[['First checks','Confirm internet access, account status, license, service health, correct time, and whether web access works. This separates account/service issues from the desktop application.'],['Outlook isolation','Check Work Offline, Outbox, mailbox quota, add-ins, credentials, data file state, and profile health. Safe Mode can help identify add-in problems.'],['Security','Never request a password. Verify identity using approved procedures before resets or MFA changes. Escalate suspected compromise immediately.'],['Checkpoint','Explain why testing Outlook on the web is a valuable isolation step.']]},
{id:'lesson-security',phase:4,cat:'support',icon:'SEC',title:'Support Security Essentials',time:'20 MIN',summary:'Protect identities, devices, data, and the organization during support work.',sections:[['Human layer','Phishing creates urgency and asks for credentials, payments, codes, or unsafe downloads. Verify unusual requests through a separate trusted channel.'],['Device layer','Use updates, approved endpoint protection, disk encryption, screen locks, backups, and least privilege. Do not disable security controls to make a symptom disappear.'],['Incident mindset','Preserve evidence, isolate only when authorized, record time and symptoms, and use the incident escalation process. Do not investigate beyond your authority.'],['Checkpoint','List three signs of phishing and the correct reporting action in your workplace.']]},
{id:'lesson-ticket',phase:4,cat:'support',icon:'TKT',title:'Tickets and Documentation',time:'16 MIN',summary:'Write support records that another technician can understand and continue.',sections:[['Good ticket structure','Record user/device, time, business impact, exact symptom, error text, scope, evidence, steps taken, results, resolution, verification, and follow-up.'],['Professional writing','Use facts instead of blame. “User reports error 0x…” is clearer than “User did it wrong.” Avoid passwords, sensitive personal data, and unnecessary confidential content.'],['Resolution note','A strong close note states the root cause when known, the change made, how success was verified, and whether prevention or monitoring is required.'],['Checkpoint','Rewrite this note: “Fixed computer. Working now.” Add evidence and verification.']]}
];
const labs=[
{id:'lab-ip',title:'Build and Test a Small Network',level:'BEGINNER / 35 MIN',desc:'Configure two clients and a gateway in Packet Tracer, then verify connectivity.',steps:['Create one router, one switch, and two PCs.','Connect devices using the correct cables.','Use network 192.168.10.0/24. Set router LAN to 192.168.10.1.','Assign unique client IPs and use 192.168.10.1 as gateway.','Ping between clients and ping the gateway.','Record the addressing table and test results.'],verify:'Both PCs must ping each other and the router. Explain why duplicate IP addresses fail.'},
{id:'lab-dns',title:'Diagnose Internet vs DNS',level:'BEGINNER / 25 MIN',desc:'Use a controlled command sequence to identify where connectivity stops.',steps:['Open Command Prompt.','Run ipconfig /all and record IPv4, gateway, and DNS.','Ping 127.0.0.1, then your local IPv4, then the default gateway.','Ping 8.8.8.8, then run nslookup example.com.','For each result, write which layer it tests.','Do not change settings unless you understand the evidence.'],verify:'Produce a five-line result table and a conclusion: device, LAN, internet route, or DNS.'},
{id:'lab-ad',title:'Create an Active Directory User',level:'BEGINNER / 40 MIN',desc:'Practice structured identity administration in your Windows Server lab.',steps:['Open Active Directory Users and Computers.','Create a Training OU.','Create a security group named IT-Lab-Users.','Create a test user using a naming standard.','Add the user to the group.','On a domain client, verify sign-in and record the result.'],verify:'The user appears in the correct OU, has group membership, and can sign in to the domain client.'},
{id:'lab-ticket',title:'Resolve and Document a Printer Issue',level:'BEGINNER / 30 MIN',desc:'Follow a support workflow and produce a professional resolution note.',steps:['Use the scenario: one user reports a network printer offline.','Write your scope and impact questions.','Create a check sequence from physical state through network and queue.','For each check, write the evidence you expect.','Assume the printer IP changed and correct the port in your simulated answer.','Write a complete ticket resolution note.'],verify:'The final note must include symptom, scope, evidence, root cause, fix, and user verification.'}
];
const quizQuestions=[
['Which service normally gives a client its IP address, subnet mask, gateway, and DNS?',['DNS','DHCP','HTTP','SMB'],1],
['A Windows client has address 169.254.20.8. What is the most likely meaning?',['It received a normal DHCP lease','It could not obtain a DHCP lease','DNS is working','The gateway is online'],1],
['Which command displays detailed Windows IP configuration?',['ipconfig /all','format','tasklist /delete','whois'],0],
['A domain name fails but pinging a public IP succeeds. Which area should you test next?',['RAM','DNS','Monitor cable','Printer spooler'],1],
['What should happen after implementing a fix?',['Close immediately','Verify full functionality and document','Delete the logs','Change another setting'],1],
['What is the safest way to assign shared folder access?',['Give every user admin rights','Use an approved security group','Share the password','Disable permissions'],1],
['Why test Outlook on the web?',['To replace Windows','To isolate account/service from desktop profile issues','To delete email','To reset the router'],1],
['Which tool shows Windows processes and resource use?',['Paint','Task Manager','Notepad','Calculator'],1],
['What is the best first response to a vague issue?',['Guess a fix','Collect symptom, scope, impact, and changes','Reinstall Windows','Replace the computer'],1],
['What belongs in a resolution note?',['A user password','Root cause, action, and verification','Blame','Unrelated personal data'],1]
];
const examQuestions=[
['A user says “Wi-Fi is connected but no sites open.” What is the best first technical check after confirming scope?',['Replace the laptop','Inspect IP, gateway, and DNS with ipconfig /all','Disable antivirus','Reset every network device'],1],
['The client has a valid IP but cannot ping its gateway. What boundary is failing?',['Local LAN path to the gateway','Only DNS','Email licensing','Printer queue'],0],
['One employee cannot sign in, but other domain users can. What should you examine first?',['Replace the domain controller','The user identity, password state, lockout, and username format','Rebuild the network','Disable MFA for everyone'],1],
['All users lose access to a shared service simultaneously. What does the scope suggest?',['Every keyboard failed','A shared service, network, or infrastructure issue','Each user forgot a password','A single local profile'],1],
['You receive a request to reset an executive password from an unknown caller. What is correct?',['Reset it quickly','Verify identity using the approved process before acting','Ask for the old password','Send a temporary password publicly'],1],
['After updating a printer TCP/IP port, what verifies the fix best?',['The settings window closed','A successful test page and user confirmation','The PC restarted','The ticket has a title'],1],
['An unknown attachment was opened and suspicious activity begins. What is the best response?',['Hide it','Follow incident procedure, preserve evidence, and escalate immediately','Delete all logs','Keep using the device normally'],1],
['Which ticket note is strongest?',['Fixed.','Restarted it.','Print failed for one user; old TCP/IP port pointed to 10.0.0.45. Updated approved port to 10.0.0.60; test page and user print succeeded.','User problem.'],2],
['A change may affect many employees. Before implementation you should consider:',['Only speed','Impact, approval, backup, and rollback','The wallpaper','Personal preference'],1],
['What makes troubleshooting professional?',['Many changes at once','Evidence, controlled tests, verification, and documentation','Confidence without checks','Always escalating immediately'],1]
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=load(),activeAssessment=null;
function load(){try{return Object.assign({completed:[],quizBest:0,examBest:0,notes:'',lastVisit:''},JSON.parse(localStorage.getItem(storeKey)||'{}'))}catch(e){return{completed:[],quizBest:0,examBest:0,notes:'',lastVisit:''}}}
function save(){localStorage.setItem(storeKey,JSON.stringify(state));updateProgress()}
async function digest(value){if(window.crypto&&window.crypto.subtle){const data=new TextEncoder().encode(value);const buf=await window.crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}return value==='ARSALAN2026'?PASS_HASH:''}
function unlock(){sessionStorage.setItem('ma-academy-unlocked','1');$('#gate').hidden=true;$('#academyApp').hidden=false;renderAll()}
$('#gateForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#passcode');const hash=await digest(input.value.trim());if(hash===PASS_HASH){$('#gateMessage').textContent='ACCESS GRANTED';setTimeout(unlock,250)}else{$('#gateMessage').textContent='ACCESS DENIED — CHECK YOUR KEY';input.select();$('.gate-card').animate([{transform:'translateX(-5px)'},{transform:'translateX(5px)'},{transform:'translateX(0)'}],{duration:220})}});
if(sessionStorage.getItem('ma-academy-unlocked')==='1')unlock();
function renderAll(){renderModules();renderRoadmap();renderLessons();renderLabs();renderAssessment('quiz');renderAssessment('exam');$('#notesText').value=state.notes;updateProgress();updateStreak()}
function isDone(id){return state.completed.includes(id)}
function toggleDone(id,force){const done=isDone(id);if(force===true&&!done)state.completed.push(id);else if(force===false&&done)state.completed=state.completed.filter(x=>x!==id);else if(force===undefined)state.completed=done?state.completed.filter(x=>x!==id):[...state.completed,id];save();renderModules();renderLessons();renderLabs();renderRoadmap()}
function updateProgress(){const total=lessons.length+labs.length,completed=[...lessons,...labs].filter(x=>isDone(x.id)).length,p=Math.round(completed/total*100);$('#overallPercent').textContent=p+'%';$('#completedLabel').textContent=`${completed} of ${total} items`;$('#progressRing').style.setProperty('--progress',p+'%');$('#statProgress').textContent=p+'%';$('#statLabs').textContent=`${labs.filter(x=>isDone(x.id)).length} / ${labs.length}`;$('#statQuiz').textContent=state.quizBest?state.quizBest+'%':'—'}
function renderModules(){const picks=[lessons[0],lessons[3],lessons[6],lessons[8]];$('#dashboardModules').innerHTML=picks.map((x,i)=>`<article class="module-card ${isDone(x.id)?'completed':''}"><span>MODULE ${String(i+1).padStart(2,'0')} / ${x.cat.toUpperCase()}</span><h3>${x.title}</h3><p>${x.summary}</p><button data-open="${x.id}" aria-label="Open ${x.title}">→</button></article>`).join('')}
function renderRoadmap(){const names=['IT Foundations','Networking Core','Windows and Identity','Service Desk Readiness'];$('#roadmapList').innerHTML=names.map((name,i)=>{const items=lessons.filter(x=>x.phase===i+1);return`<article class="roadmap-phase"><div class="phase-number">PHASE ${String(i+1).padStart(2,'0')}</div><div class="phase-content"><h2>${name}</h2><p>${items.filter(x=>isDone(x.id)).length} of ${items.length} lessons completed</p><div class="phase-items">${items.map(x=>`<button data-open="${x.id}">${isDone(x.id)?'✓ ':''}${x.title}</button>`).join('')}</div></div></article>`}).join('')}
function renderLessons(filter='all',query=''){const list=lessons.filter(x=>(filter==='all'||x.cat===filter)&&(`${x.title} ${x.summary} ${x.cat}`.toLowerCase().includes(query.toLowerCase())));$('#lessonGrid').innerHTML=list.length?list.map((x,i)=>`<article class="lesson-card ${isDone(x.id)?'completed':''}"><div class="lesson-icon">${x.icon}</div><h2>${x.title}</h2><p>${x.summary}</p><div class="lesson-meta"><span>${x.cat.toUpperCase()}</span><span>${x.time}</span></div><button data-open="${x.id}" aria-label="Open ${x.title}"></button></article>`).join(''):'<div class="search-empty">No learning content matches your search.</div>'}
function renderLabs(query=''){const list=labs.filter(x=>(`${x.title} ${x.desc}`.toLowerCase().includes(query.toLowerCase())));$('#labList').innerHTML=list.length?list.map((x,i)=>`<article class="lab-card ${isDone(x.id)?'completed':''}"><div class="lab-index">${String(i+1).padStart(2,'0')}</div><div class="lab-info"><span>${x.level}</span><h2>${x.title}</h2><p>${x.desc}</p></div><div class="lab-actions"><button data-open="${x.id}">OPEN LAB</button><button class="complete" data-complete="${x.id}">${isDone(x.id)?'✓ COMPLETED':'MARK COMPLETE'}</button></div></article>`).join(''):'<div class="search-empty">No labs match your search.</div>'}
function openContent(id){const item=[...lessons,...labs].find(x=>x.id===id);if(!item)return;let html;if(item.sections){html=`<div class="dialog-content"><p class="kicker">LESSON / ${item.cat.toUpperCase()} / ${item.time}</p><h1>${item.title}</h1><p class="summary">${item.summary}</p>${item.sections.map(s=>`<section class="lesson-section"><h2>${s[0]}</h2>${s[0].toLowerCase().includes('command')?`<div class="command-box">${s[1]}</div>`:`<p>${s[1]}</p>`}</section>`).join('')}<div class="dialog-footer"><span class="kicker">LEARN → PRACTICE → VERIFY</span><button data-dialog-complete="${item.id}" class="${isDone(item.id)?'done':''}">${isDone(item.id)?'✓ LESSON COMPLETED':'MARK LESSON COMPLETE'}</button></div></div>`}else{html=`<div class="dialog-content"><p class="kicker">PRACTICE LAB / ${item.level}</p><h1>${item.title}</h1><p class="summary">${item.desc}</p><section class="lesson-section"><h2>Lab procedure</h2><ol>${item.steps.map(s=>`<li>${s}</li>`).join('')}</ol></section><section class="lesson-section"><h2>Verification standard</h2><p>${item.verify}</p></section><div class="dialog-footer"><span class="kicker">DO NOT GUESS — RECORD EVIDENCE</span><button data-dialog-complete="${item.id}" class="${isDone(item.id)?'done':''}">${isDone(item.id)?'✓ LAB COMPLETED':'MARK LAB COMPLETE'}</button></div></div>`}$('#dialogBody').innerHTML=html;$('#contentDialog').showModal()}
function renderAssessment(type){const area=$(`#${type}Area`),best=type==='quiz'?state.quizBest:state.examBest,count=(type==='quiz'?quizQuestions:examQuestions).length;area.innerHTML=`<div class="assessment-start"><strong>${best?best+'%':count}</strong><h2>${best?'Best score':'Questions ready'}</h2><p>${type==='quiz'?'A focused course knowledge check.':'A scenario-based final assessment covering safe support decisions.'}<br>Your best result is saved on this device.</p><button class="start-btn" data-start="${type}">${best?'TRY AGAIN':'START '+type.toUpperCase()} →</button></div>`}
function startAssessment(type){activeAssessment={type,index:0,answers:[]};showQuestion()}
function showQuestion(){const a=activeAssessment,qs=a.type==='quiz'?quizQuestions:examQuestions,q=qs[a.index],area=$(`#${a.type}Area`);area.innerHTML=`<div class="question"><div class="question-head"><span>${a.type.toUpperCase()} / QUESTION ${a.index+1}</span><span>${a.index+1} OF ${qs.length}</span></div><h2>${q[0]}</h2><div class="answers">${q[1].map((v,i)=>`<button class="answer" data-answer="${i}"><b>${String.fromCharCode(65+i)}.</b> ${v}</button>`).join('')}</div><div class="question-actions"><button class="next-btn" disabled>${a.index===qs.length-1?'SUBMIT ASSESSMENT':'NEXT QUESTION →'}</button></div></div>`}
function finishAssessment(){const a=activeAssessment,qs=a.type==='quiz'?quizQuestions:examQuestions,correct=a.answers.filter((v,i)=>v===qs[i][2]).length,score=Math.round(correct/qs.length*100),pass=score>=80;if(a.type==='quiz')state.quizBest=Math.max(state.quizBest,score);else state.examBest=Math.max(state.examBest,score);save();const area=$(`#${a.type}Area`);area.innerHTML=`<div class="result"><p class="kicker">${pass?'ASSESSMENT PASSED':'MORE PRACTICE NEEDED'}</p><strong>${score}%</strong><h2>${correct} of ${qs.length} correct</h2><p>${pass?'Strong work. Review your notes and continue practicing the workflow in real labs.':'Review the relevant lessons, repeat the practical labs, and try again. Accuracy matters more than speed.'}</p><button data-start="${a.type}">RETAKE ${a.type.toUpperCase()}</button></div>`;activeAssessment=null;updateProgress()}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('#academyNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function updateStreak(){const today=new Date().toISOString().slice(0,10),last=state.lastVisit;state.lastVisit=today;save();$('#statStreak').textContent=last===today?'1 DAY':'1 DAY'}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)openContent(open.dataset.open);const jump=e.target.closest('[data-view-jump]');if(jump)showView(jump.dataset.viewJump);const nav=e.target.closest('#academyNav [data-view]');if(nav)showView(nav.dataset.view);const comp=e.target.closest('[data-complete]');if(comp)toggleDone(comp.dataset.complete);const dialogComp=e.target.closest('[data-dialog-complete]');if(dialogComp){toggleDone(dialogComp.dataset.dialogComplete);openContent(dialogComp.dataset.dialogComplete)}const start=e.target.closest('[data-start]');if(start)startAssessment(start.dataset.start);const ans=e.target.closest('[data-answer]');if(ans&&activeAssessment){$$('.answer').forEach(x=>x.classList.remove('selected'));ans.classList.add('selected');activeAssessment.answers[activeAssessment.index]=Number(ans.dataset.answer);$('.next-btn').disabled=false}const next=e.target.closest('.next-btn');if(next&&activeAssessment){const qs=activeAssessment.type==='quiz'?quizQuestions:examQuestions;if(activeAssessment.index<qs.length-1){activeAssessment.index++;showQuestion()}else finishAssessment()}});
$('#dialogClose').onclick=()=>$('#contentDialog').close();$('#contentDialog').addEventListener('click',e=>{if(e.target===$('#contentDialog'))$('#contentDialog').close()});$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#lockButton').onclick=()=>{sessionStorage.removeItem('ma-academy-unlocked');location.reload()};
$('#themeButton').onclick=()=>{const t=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=t;localStorage.setItem('portfolio-theme',t);$('#themeButton').textContent=t==='light'?'☀':'☾'};
$$('#lessonFilters button').forEach(b=>b.onclick=()=>{$$('#lessonFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLessons(b.dataset.filter,$('#searchInput').value)});
$('#searchInput').addEventListener('input',e=>{showView('lessons');$$('#lessonFilters button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderLessons('all',e.target.value)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape')$('#sidebar').classList.remove('open')});
let noteTimer;$('#notesText').addEventListener('input',e=>{clearTimeout(noteTimer);$('#notesStatus').textContent='Saving…';noteTimer=setTimeout(()=>{state.notes=e.target.value;save();$('#notesStatus').textContent='Saved automatically'},400)});$('#exportNotes').onclick=()=>{const blob=new Blob([`MUHAMMAD ARSALAN — IT SUPPORT ACADEMY NOTES\nExported: ${new Date().toLocaleString()}\n\n${state.notes}`],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Muhammad-Arsalan-Academy-Notes.txt';a.click();URL.revokeObjectURL(a.href)};
function downloadFile(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),100)}
$('#exportProgress').onclick=()=>downloadFile('Muhammad-Arsalan-Academy-Backup.json',JSON.stringify({academy:'Muhammad Arsalan Private IT Support Academy',version:1,exportedAt:new Date().toISOString(),state},null,2),'application/json');
$('#importProgress').addEventListener('change',event=>{const file=event.target.files&&event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data||!data.state||!Array.isArray(data.state.completed))throw new Error('Invalid backup');state=Object.assign({completed:[],quizBest:0,examBest:0,notes:'',lastVisit:''},data.state);save();renderAll();alert('Academy backup imported successfully.')}catch(error){alert('This file is not a valid Academy backup.')}event.target.value=''};reader.readAsText(file)});
$('#resetProgress').onclick=()=>{if(!confirm('Reset all lesson progress, scores and notes? Export a backup first if you want to keep them.'))return;state={completed:[],quizBest:0,examBest:0,notes:'',lastVisit:''};save();renderAll();showView('courses')};
})();
