(()=>{'use strict';
const KEY='academy-os-content-v1',clone=v=>JSON.parse(JSON.stringify(v)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),slug=v=>String(v||'record').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
let stored;try{stored=JSON.parse(localStorage.getItem(KEY))}catch{}let courses=stored?.version===1&&Array.isArray(stored.courses)?stored.courses:clone(window.ACADEMY_COURSES),selected=null,dirty=false,libraryDirty=false,undo=null,treeFilter='all';
function normalizeCourse(course,index){const c={...course,id:course?.id||`course-${index+1}`,slug:course?.slug||course?.id||`course-${index+1}`,title:course?.title||`Untitled course ${index+1}`,summary:course?.summary||'',level:course?.level||'Beginner',skills:Array.isArray(course?.skills)?course.skills:[],published:course?.published!==false,modules:Array.isArray(course?.modules)?course.modules:[]};c.modules=c.modules.map((module,mi)=>({...module,id:module?.id||`module-${mi+1}`,title:module?.title||`Untitled module ${mi+1}`,description:module?.description||'',topics:(Array.isArray(module?.topics)?module.topics:[]).map((topic,ti)=>({...topic,id:topic?.id||`${c.id}-topic-${ti+1}`,title:topic?.title||`Untitled topic ${ti+1}`,time:topic?.time||'20 min',skills:Array.isArray(topic?.skills)?topic.skills:[],objectives:Array.isArray(topic?.objectives)?topic.objectives:[],prerequisites:Array.isArray(topic?.prerequisites)?topic.prerequisites:[],blocks:Array.isArray(topic?.blocks)?topic.blocks:[],practical:topic?.practical&&typeof topic.practical==='object'?topic.practical:{title:'Practical task',steps:[],required:true},quiz:topic?.quiz&&typeof topic.quiz==='object'?topic.quiz:{passingScore:70,questions:[]}}))}));return c}
courses=(Array.isArray(courses)?courses:[]).map(normalizeCourse);if(!courses.length)courses=clone(window.ACADEMY_COURSES||[]).map(normalizeCourse);
if(courses.length)selected={type:'course',c:0};
if(stored?.draft)libraryDirty=true;
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)],topics=()=>courses.flatMap(c=>c.modules.flatMap(m=>m.topics));
function item(){if(!selected)return null;if(selected.type==='course')return courses[selected.c]||null;if(selected.type==='module')return courses[selected.c]?.modules[selected.m]||null;if(selected.type==='topic')return courses[selected.c]?.modules[selected.m]?.topics[selected.t]||null;return null}
const input=(id,label,value='',wide=false,help='')=>`<label class="field ${wide?'wide':''}"><span>${label}</span><input id="${id}" value="${esc(value)}">${help?`<small>${help}</small>`:''}</label>`,area=(id,label,value='',cls='')=>`<label class="field wide"><span>${label}</span><textarea id="${id}" class="${cls}">${esc(value)}</textarea></label>`;
const blockTypes=['paragraph','definition','ordered-list','command','scenario','warning','tip','example'];
const selectOptions=(values,current)=>values.map(v=>`<option value="${v}" ${v===current?'selected':''}>${v.replace('-', ' ')}</option>`).join('');
function blockCard(b={},i=0){const list=Array.isArray(b.items),content=list?b.items.join('\n'):(b.body||'');return `<article class="builder-card" data-block><div class="builder-head"><strong>Content block ${i+1}</strong><button type="button" class="icon-danger" data-remove-block aria-label="Remove content block">Remove</button></div><div class="builder-grid"><label class="field"><span>Block type</span><select data-block-type>${selectOptions(blockTypes,b.type||'paragraph')}</select></label><label class="field"><span>Heading</span><input data-block-title value="${esc(b.title||'')}"></label><label class="field wide"><span>Content</span><textarea data-block-content placeholder="Write the explanation here. For lists or commands, use one item per line.">${esc(content)}</textarea><small>Lists and commands use one item per line.</small></label></div></article>`}
function blocksEditor(items=[]){return `<section class="section builder-section"><div class="section-head"><div><h3>Lesson content</h3><p>Build the lesson from clear, reusable content blocks.</p></div><button type="button" data-add-block>+ Add block</button></div><div id="blockList" class="builder-list">${items.map(blockCard).join('')}</div></section>`}
function practicalEditor(p={}){return `<section class="section builder-section"><div class="section-head"><div><h3>Practical activity</h3><p>Give learners a concrete task to complete.</p></div></div><div class="grid compact">${input('practicalTitle','Activity title',p.title||'Practical task',true)}${area('practicalSteps','Steps — one per line',(p.steps||[]).join('\n'))}<label class="toggle field wide"><input id="practicalRequired" type="checkbox" ${p.required===false?'':'checked'}><span>Required for completion</span></label></div></section>`}
function questionCard(q={},i=0){const opts=q.options||['Option 1','Option 2'],shown=Array.isArray(q.answer)?q.answer.map(n=>n+1).join(', '):(q.answer??0)+1;return `<article class="builder-card" data-question data-question-id="${esc(q.id||'')}"><div class="builder-head"><strong>Question ${i+1}</strong><button type="button" class="icon-danger" data-remove-question aria-label="Remove question">Remove</button></div><div class="builder-grid"><label class="field"><span>Question type</span><select data-question-type>${selectOptions(['multiple-choice','multiple-select','true-false'],q.type||'multiple-choice')}</select></label><label class="field"><span>Correct answer</span><input data-question-answer value="${esc(shown)}" inputmode="numeric"><small>Use option number starting at 1. For multiple answers: 1, 3.</small></label><label class="field wide"><span>Question</span><input data-question-text value="${esc(q.text||'')}"></label><label class="field wide"><span>Answer options — one per line</span><textarea data-question-options>${esc(opts.join('\n'))}</textarea></label><label class="field wide"><span>Explanation</span><textarea data-question-explanation>${esc(q.explanation||'')}</textarea></label></div></article>`}
function quizEditor(q={}){return `<section class="section builder-section"><div class="section-head"><div><h3>Knowledge check</h3><p>Add questions and explain why each answer is correct.</p></div><button type="button" data-add-question>+ Add question</button></div><label class="field score-field"><span>Passing score (%)</span><input id="passingScore" type="number" min="0" max="100" value="${esc(q.passingScore??70)}"></label><div id="questionList" class="builder-list">${(q.questions||[]).map(questionCard).join('')}</div></section>`}
function stats(updateCount=true){const modules=courses.reduce((n,c)=>n+c.modules.length,0),ts=topics().length,published=courses.filter(c=>c.published!==false).length;$('#adminStats').innerHTML=[['COURSES',courses.length],['PUBLISHED',published],['MODULES',modules],['TOPICS',ts]].map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');if(updateCount)$('#recordCount').textContent=`${courses.length+modules+ts} records`}
function courseHasIssues(c){return!c.summary||!c.modules.length||c.modules.some(m=>!m.description||!m.topics.length||m.topics.some(t=>!t.objectives?.length||!t.blocks?.length||!t.practical?.steps?.length||!t.quiz?.questions?.length))}
function tree(){const q=$('#treeSearch').value.trim().toLowerCase();let visible=0;$('#adminTree').innerHTML=courses.map((c,ci)=>{const text=[c.title,...c.modules.flatMap(m=>[m.title,...m.topics.map(t=>t.title)])].join(' ').toLowerCase(),matchesFilter=treeFilter==='all'||(treeFilter==='draft'&&c.published===false)||(treeFilter==='issues'&&courseHasIssues(c));if((q&&!text.includes(q))||!matchesFilter)return'';visible++;return`<section class="tree-course"><div class="tree-row course-row"><button class="tree-record ${selected?.type==='course'&&selected.c===ci?'active':''}" data-select="course,${ci}" type="button"><small>COURSE · ${c.published===false?'DRAFT':'PUBLISHED'}${courseHasIssues(c)?' · NEEDS WORK':''}</small><strong>${esc(c.title)}</strong><span>${c.modules.length} ${c.modules.length===1?'module':'modules'}</span></button><button class="tree-add" data-create-module="${ci}" type="button" aria-label="Add module to ${esc(c.title)}" title="Add module"><span aria-hidden="true">+</span></button></div><div class="tree-nested module-group">${c.modules.map((m,mi)=>`<div class="tree-branch"><div class="tree-row module-row"><button class="tree-record ${selected?.type==='module'&&selected.c===ci&&selected.m===mi?'active':''}" data-select="module,${ci},${mi}" type="button"><small>MODULE ${mi+1}</small><strong>${esc(m.title)}</strong><span>${m.topics.length} ${m.topics.length===1?'topic':'topics'}</span></button><button class="tree-add" data-create-topic="${ci},${mi}" type="button" aria-label="Add topic to ${esc(m.title)}" title="Add topic"><span aria-hidden="true">+</span></button></div><div class="tree-nested topic-group">${m.topics.map((t,ti)=>`<button class="tree-record topic-record ${selected?.type==='topic'&&selected.c===ci&&selected.m===mi&&selected.t===ti?'active':''}" data-select="topic,${ci},${mi},${ti}" type="button"><small>TOPIC ${ti+1}</small><strong>${esc(t.title)}</strong><span>${esc(t.time||'20 min')}</span></button>`).join('')}</div></div>`).join('')}</div></section>`}).join('')||`<div class="tree-empty-state"><strong>No ${treeFilter==='all'?'matching':treeFilter} content</strong><p>${q?'Try a different search term.':'Choose another filter or create a course.'}</p></div>`;$('#recordCount').textContent=`${visible} ${visible===1?'course':'courses'} shown`;stats(false)}
function select(next){if(dirty&&!confirm('Discard unapplied changes in the open form?'))return;selected=next;dirty=false;tree();form();requestAnimationFrame(()=>{$('.editor').scrollTop=0})}
function form(){const x=item();if(!x){$('#recordForm').hidden=true;health();return}$('#recordForm').hidden=false;$('#kindLabel').textContent=selected.type.toUpperCase();$('#formTitle').textContent=x.title;const c=courses[selected.c],m=selected.m===undefined?null:c.modules[selected.m];$('#recordPath').innerHTML=`<span>${esc(c.title)}</span>${m?`<i aria-hidden="true">/</i><span>${esc(m.title)}</span>`:''}${selected.type==='topic'?`<i aria-hidden="true">/</i><b>${esc(x.title)}</b>`:''}`;$('#errors').hidden=true;
 let html;if(selected.type==='course')html=`<div class="grid">${input('title','Course title',x.title)}${input('id','Course slug',x.slug||x.id)}${input('level','Level',x.level||'Beginner')}${input('skills','Skill tags',(x.skills||[]).join(', '))}${area('summary','Description',x.summary||'')}<label class="toggle field wide"><input id="published" type="checkbox" ${x.published===false?'':'checked'}><span>Published</span></label></div>`;
 if(selected.type==='module')html=`<div class="grid">${input('title','Module title',x.title)}${input('id','Module ID',x.id)}${area('description','Description',x.description||'')}</div>`;
 if(selected.type==='topic')html=`<div class="grid">${input('title','Topic title',x.title)}${input('id','Topic ID',x.id)}${input('time','Estimated time',x.time||'20 min')}${input('skills','Skill tags',(x.skills||[]).join(', '),false,'Separate tags with commas.')}${area('objectives','Learning objectives — one per line',(x.objectives||[]).join('\n'))}${area('prerequisites','Required prerequisite topic IDs — one per line',(x.prerequisites||[]).filter(p=>p.type==='required').map(p=>p.topicId).join('\n'))}${blocksEditor(x.blocks||[])}${practicalEditor(x.practical||{})}${quizEditor(x.quiz||{})}</div>`;
 $('#fields').innerHTML=html;const {list,index}=collection();$('#moveUp').disabled=index===0;$('#moveDown').disabled=index===list.length-1;$('#addChildBtn').hidden=selected.type==='topic';$('#addChildBtn').textContent=selected.type==='course'?'+ Add module':'+ Add topic';health()}
function readBlocks(){return $$('[data-block]').map(card=>{const type=$('[data-block-type]',card).value,title=$('[data-block-title]',card).value.trim(),content=$('[data-block-content]',card).value.trim();return ['ordered-list','command'].includes(type)?{type,title,items:lines(content)}:{type,title,body:content}})}
function readPractical(){return{title:$('#practicalTitle').value.trim(),steps:lines($('#practicalSteps').value),required:$('#practicalRequired').checked}}
function readQuiz(errors){const score=Number($('#passingScore').value),questions=$$('[data-question]').map((card,i)=>{const type=$('[data-question-type]',card).value,text=$('[data-question-text]',card).value.trim(),options=lines($('[data-question-options]',card).value),raw=$('[data-question-answer]',card).value,answerNumbers=csv(raw).map(Number),answer=type==='multiple-select'?answerNumbers.map(n=>n-1):(answerNumbers[0]||1)-1;if(!text)errors.push(`Question ${i+1} needs question text.`);if(options.length<2)errors.push(`Question ${i+1} needs at least two options.`);const answers=Array.isArray(answer)?answer:[answer];if(answers.some(n=>!Number.isInteger(n)||n<0||n>=options.length))errors.push(`Question ${i+1} has an answer outside its option list.`);return{id:card.dataset.questionId||`q-${Date.now().toString(36)}-${i+1}`,type,text,options,answer,explanation:$('[data-question-explanation]',card).value.trim()}});if(!Number.isFinite(score)||score<0||score>100)errors.push('Passing score must be between 0 and 100.');return{passingScore:score,questions}}
function apply(e){e?.preventDefault();const x=item(),errors=[],title=$('#title').value.trim();if(!title)errors.push('Title is required.');
 if(selected.type==='course'){const id=slug($('#id').value);if(courses.some((c,i)=>i!==selected.c&&c.id===id))errors.push('Course slug must be unique.');if(!errors.length)Object.assign(x,{title,id,slug:id,level:$('#level').value.trim(),skills:csv($('#skills').value),summary:$('#summary').value.trim(),published:$('#published').checked})}
 if(selected.type==='module'){const id=slug($('#id').value);if(courses[selected.c].modules.some((m,i)=>i!==selected.m&&m.id===id))errors.push('Module ID must be unique in its course.');if(!errors.length)Object.assign(x,{title,id,description:$('#description').value.trim()})}
 if(selected.type==='topic'){const id=slug($('#id').value),blocks=readBlocks(),practical=readPractical(),quiz=readQuiz(errors);if(topics().some(t=>t!==x&&t.id===id))errors.push('Topic ID must be unique.');if(blocks.some((b,i)=>!b.title||(!b.body&&!b.items?.length)))errors.push('Each content block needs a heading and content.');if(!practical.title&&practical.steps.length)errors.push('The practical activity needs a title.');const prerequisites=lines($('#prerequisites').value).map(topicId=>({topicId,type:'required'}));prerequisites.forEach(p=>{if(!topics().some(t=>t.id===p.topicId))errors.push(`Prerequisite "${p.topicId}" does not exist.`);if(p.topicId===id)errors.push('A topic cannot require itself.')});if(!errors.length)Object.assign(x,{title,id,time:$('#time').value.trim(),skills:csv($('#skills').value),objectives:lines($('#objectives').value),prerequisites,blocks,practical,quiz})}
 if(errors.length)return showErrors(errors);dirty=false;libraryDirty=true;persistLocalDraft();$('#saveState').textContent='Draft saved locally · ready to publish';setSync('draft','Draft not published');tree();form();toast('Draft saved locally.');return true}
const csv=v=>v.split(',').map(x=>x.trim()).filter(Boolean),lines=v=>v.split('\n').map(x=>x.trim()).filter(Boolean);
function showErrors(list){const el=$('#errors');el.hidden=false;el.innerHTML=`<strong>Fix these problems:</strong><ul>${list.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;el.focus();return false}
function collection(){if(selected.type==='course')return{list:courses,index:selected.c};if(selected.type==='module')return{list:courses[selected.c].modules,index:selected.m};return{list:courses[selected.c].modules[selected.m].topics,index:selected.t}}
function createCourse(){const n=courses.length+1,id=`course-${n}`;courses.push({id,slug:id,title:`New course ${n}`,level:'Beginner',summary:'',skills:[],published:false,completionRules:{requiredTopicCompletion:100,finalAssessmentScore:70},modules:[]});persistDirty();select({type:'course',c:courses.length-1})}
function createModule(c){const a=courses[c].modules,n=a.length+1;a.push({id:`module-${n}`,title:`New module ${n}`,description:'',topics:[]});persistDirty();select({type:'module',c,m:a.length-1})}
function createTopic(c,m){const a=courses[c].modules[m].topics,n=a.length+1;a.push({id:`${courses[c].id}-topic-${n}`,title:`New topic ${n}`,time:'20 min',skills:[],prerequisites:[],objectives:[],blocks:[],practical:{title:'Practical task',steps:[],required:true},quiz:{passingScore:70,questions:[]}});persistDirty();select({type:'topic',c,m,t:a.length-1})}
function duplicate(){if(dirty&&!apply())return;const {list,index}=collection(),copy=clone(item());copy.title+=' copy';if(selected.type==='course'){copy.id=copy.slug=slug(copy.id+'-copy-'+Date.now().toString().slice(-4));copy.published=false}else if(selected.type==='module')copy.id=slug(copy.id+'-copy-'+Date.now().toString().slice(-4));else{copy.id=slug(copy.id+'-copy-'+Date.now().toString().slice(-4));copy.prerequisites=[]}list.splice(index+1,0,copy);persistDirty();const n={...selected};if(n.type==='course')n.c++;else if(n.type==='module')n.m++;else n.t++;select(n);toast('Record duplicated.')}
function remove(){const x=item();if(selected.type==='course'&&courses.length===1)return toast('Create another course before deleting the final course.');if(!confirm(`Delete "${x.title}"?`))return;const {list,index}=collection();undo={item:clone(x),selected:{...selected},index};list.splice(index,1);selected=null;dirty=false;$('#undoBtn').hidden=false;persistDirty();tree();form();toast('Deleted. You can undo before saving.')}
function undoDelete(){if(!undo)return;const p=undo.selected;let list=p.type==='course'?courses:p.type==='module'?courses[p.c]?.modules:courses[p.c]?.modules[p.m]?.topics;if(!list)return toast('Parent record no longer exists.');list.splice(Math.min(undo.index,list.length),0,undo.item);selected={...p};if(p.type==='course')selected.c=Math.min(undo.index,list.length-1);if(p.type==='module')selected.m=Math.min(undo.index,list.length-1);if(p.type==='topic')selected.t=Math.min(undo.index,list.length-1);undo=null;$('#undoBtn').hidden=true;persistDirty();tree();form();toast('Deletion undone.')}
function move(d){if(dirty&&!apply())return;const {list,index}=collection(),to=index+d;if(to<0||to>=list.length)return;[list[index],list[to]]=[list[to],list[index]];if(selected.type==='course')selected.c=to;else if(selected.type==='module')selected.m=to;else selected.t=to;persistDirty();tree();form()}
function persistLocalDraft(){try{stored={version:1,savedAt:new Date().toISOString(),draft:true,courses};localStorage.setItem(KEY,JSON.stringify(stored));return true}catch(error){console.warn('Local draft could not be saved.',error);toast('Local draft could not be saved. Export a backup.');return false}}
function persistDirty(){libraryDirty=true;persistLocalDraft();$('#saveState').textContent='Draft saved locally · not published';setSync('draft','Draft not published')}
function setSync(state,label){const badge=$('#syncBadge');if(!badge)return;badge.dataset.state=state;badge.textContent=label}
function validate(){const errors=[];if(!courses.length)errors.push('At least one course is required.');const ids=new Set();topics().forEach(t=>{if(ids.has(t.id))errors.push(`Duplicate topic ID: ${t.id}`);ids.add(t.id)});topics().forEach(t=>(t.prerequisites||[]).forEach(p=>{if(!ids.has(p.topicId))errors.push(`${t.title} has missing prerequisite ${p.topicId}.`)}));courses.filter(c=>c.published!==false).forEach(c=>{if(!c.modules.length)errors.push(`Published course "${c.title}" has no modules.`);c.modules.forEach(m=>{if(!m.topics.length)errors.push(`Published module "${m.title}" has no topics.`)})});return errors}
async function save(){if(dirty&&!apply())return;const errors=validate();if(errors.length){if(item())showErrors(errors);else toast(errors[0]);return}const payload={version:1,savedAt:new Date().toISOString(),draft:true,courses};const button=$('#saveLibrary');button.disabled=true;button.textContent='Publishing…';setSync('syncing','Publishing…');try{stored=payload;localStorage.setItem(KEY,JSON.stringify(payload));undo=null;libraryDirty=false;$('#undoBtn').hidden=true;$('#saveState').textContent=window.PortfolioAPI?'Draft safe · publishing':'Library saved locally';if(window.PortfolioAPI){const result=await window.PortfolioAPI.saveAcademyLibrary(courses);stored={...payload,draft:false,publishedAt:result?.updatedAt||new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(stored));$('#saveState').textContent='Published successfully';setSync('synced','Cloud published');toast('Course library published.')}else{setSync('local','Saved locally');toast('Course library saved locally.')}}catch(error){libraryDirty=true;$('#saveState').textContent='Draft safe · cloud unavailable';setSync('offline','Cloud unavailable');toast('Local draft is safe. Cloud publish failed; sign in or try again.');console.warn('Academy library publish failed.',error)}finally{button.disabled=false;button.textContent='Publish changes'}}
function previewData(){const x=item();if(!x||!dirty)return x;if(selected.type==='course')return{...x,title:$('#title')?.value.trim()||x.title,summary:$('#summary')?.value.trim()||'',level:$('#level')?.value.trim()||'',skills:csv($('#skills')?.value||'')};if(selected.type==='module')return{...x,title:$('#title')?.value.trim()||x.title,description:$('#description')?.value.trim()||''};return{...x,title:$('#title')?.value.trim()||x.title,time:$('#time')?.value.trim()||'',skills:csv($('#skills')?.value||''),objectives:lines($('#objectives')?.value||''),blocks:readBlocks(),practical:readPractical(),quiz:readQuiz([])}}
function renderPreview(){const x=previewData(),el=$('#contentPreview');if(!x){el.innerHTML='<p>Select a record to see a learner-facing preview.</p>';return}const live=dirty?'<span class="preview-live">LIVE FORM PREVIEW</span>':'<span class="preview-saved">SAVED DRAFT</span>';if(selected.type==='course'){el.innerHTML=`<article class="preview-card course-preview">${live}<small>${esc(x.level||'Course')}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary||'Add a course description to help learners understand the outcome.')}</p><div class="preview-tags">${(x.skills||[]).map(s=>`<span>${esc(s)}</span>`).join('')}</div><dl><div><dt>Modules</dt><dd>${x.modules.length}</dd></div><div><dt>Status</dt><dd>${x.published===false?'Draft':'Published'}</dd></div></dl></article>`}else if(selected.type==='module'){el.innerHTML=`<article class="preview-card">${live}<small>MODULE</small><h3>${esc(x.title)}</h3><p>${esc(x.description||'Add a concise module description.')}</p><ol class="preview-list">${x.topics.map((t,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><b>${esc(t.title)}</b><small>${esc(t.time||'')}</small></li>`).join('')||'<li class="empty">No topics yet</li>'}</ol></article>`}else{el.innerHTML=`<article class="preview-card topic-preview">${live}<small>${esc(x.time||'TOPIC')}</small><h3>${esc(x.title)}</h3><div class="preview-objectives"><b>Learning outcomes</b><ul>${(x.objectives||[]).map(o=>`<li>${esc(o)}</li>`).join('')||'<li>Add at least one outcome.</li>'}</ul></div><div class="preview-blocks">${(x.blocks||[]).map(b=>`<section><span>${esc(b.type)}</span><strong>${esc(b.title)}</strong><p>${esc(b.body||(b.items||[]).join(' · '))}</p></section>`).join('')||'<p>No lesson blocks yet.</p>'}</div><div class="preview-summary"><span>${x.practical?.steps?.length||0}<small>practice steps</small></span><span>${x.quiz?.questions?.length||0}<small>questions</small></span></div></article>`}}
function health(){const x=item();renderPreview();if(!x){$('#health').innerHTML='<p>Select a record to see validation and completeness.</p>';return}const checks=selected.type==='course'?[['Title',x.title],['Description',x.summary],['Skills',x.skills?.length],['Modules',x.modules?.length]]:selected.type==='module'?[['Title',x.title],['Description',x.description],['Topics',x.topics?.length]]:[['Title',x.title],['Objectives',x.objectives?.length],['Content blocks',x.blocks?.length],['Practical task',x.practical?.title],['Questions',x.quiz?.questions?.length]],score=Math.round(checks.filter(c=>c[1]).length/checks.length*100);$('#health').innerHTML=`<div class="health-card compact"><div><strong>${score}%</strong><p>Complete</p></div><ul>${checks.map(c=>`<li class="${c[1]?'':'bad'}"><span>${c[0]}</span><b>${c[1]?'Ready':'Missing'}</b></li>`).join('')}</ul></div>`}
function exportFile(){const b=new Blob([JSON.stringify({schema:'academy-os-content',version:1,exportedAt:new Date().toISOString(),courses},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='academy-os-content.json';a.click();URL.revokeObjectURL(u)}
async function importFile(f){try{const d=JSON.parse(await f.text());if(d.schema!=='academy-os-content'||!d.courses?.length)throw Error();courses=clone(d.courses).map(normalizeCourse);selected=null;dirty=false;persistDirty();tree();form();toast('Imported as a draft. Review it, then publish.')}catch{toast('Import failed: invalid Academy OS file.')}}
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2500)}
function markFormDirty(){dirty=true;$('#saveState').textContent='Form changes not applied';setSync('draft','Draft not published');renderPreview()}
function updateThemeButton(){const button=$('#adminTheme'),dark=document.documentElement.dataset.theme==='dark';if(!button)return;button.setAttribute('aria-pressed',String(dark));button.textContent=dark?'Light theme':'Dark theme'}
function toggleTheme(){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('portfolio-theme',next)}catch{}updateThemeButton()}
function builderAction(e){if(e.target.closest('[data-add-block]')){$('#blockList').insertAdjacentHTML('beforeend',blockCard({},$$('[data-block]').length));markFormDirty()}const removeBlock=e.target.closest('[data-remove-block]');if(removeBlock){removeBlock.closest('[data-block]').remove();markFormDirty()}if(e.target.closest('[data-add-question]')){$('#questionList').insertAdjacentHTML('beforeend',questionCard({},$$('[data-question]').length));markFormDirty()}const removeQuestion=e.target.closest('[data-remove-question]');if(removeQuestion){removeQuestion.closest('[data-question]').remove();markFormDirty()}}
function preview(){if(dirty&&!apply())return;const x=item();if(!x)return;const hash=selected.type==='topic'?`#topic/${encodeURIComponent(x.id)}`:selected.type==='course'?'#course':'#home';window.open(`academy.html${hash}`,'_blank','noopener')}
function showInspectorTab(name){const previewActive=name==='preview';$('#previewTab').setAttribute('aria-selected',String(previewActive));$('#healthTab').setAttribute('aria-selected',String(!previewActive));$('#previewPanel').hidden=!previewActive;$('#healthPanel').hidden=previewActive;$('#inspectorTitle').textContent=previewActive?'Learner preview':'Content health'}
function toggleInspector(force){const workspace=$('.workspace'),next=typeof force==='boolean'?force:workspace.classList.contains('inspector-collapsed');workspace.classList.toggle('inspector-collapsed',!next);$('#inspectorToggle').setAttribute('aria-pressed',String(next));if(next)showInspectorTab('preview')}
function toggleFocus(){const workspace=$('.workspace'),active=!workspace.classList.contains('focus-mode');workspace.classList.toggle('focus-mode',active);$('#focusModeBtn').setAttribute('aria-pressed',String(active));$('#focusModeBtn').textContent=active?'Exit focus':'Focus'}
function addChild(){if(dirty&&!apply())return;if(selected?.type==='course')createModule(selected.c);else if(selected?.type==='module')createTopic(selected.c,selected.m)}
function setupEnhancedTools(){$('#addChildBtn').onclick=addChild;$('#focusModeBtn').onclick=toggleFocus;$('#inspectorToggle').onclick=()=>toggleInspector();$('#closeInspector').onclick=()=>toggleInspector(false);$('#previewTab').onclick=()=>showInspectorTab('preview');$('#healthTab').onclick=()=>showInspectorTab('health')}
function boot(){try{tree();form();updateThemeButton();setSync(window.PortfolioAPI?'syncing':'local',window.PortfolioAPI?'Checking cloud…':'Local draft ready');$('#adminTree').addEventListener('click',e=>{const s=e.target.closest('[data-select]'),m=e.target.closest('[data-create-module]'),t=e.target.closest('[data-create-topic]');if(s){const [type,c,mi,ti]=s.dataset.select.split(',');select({type,c:+c,m:mi===undefined?undefined:+mi,t:ti===undefined?undefined:+ti})}else if(m)createModule(+m.dataset.createModule);else if(t){const [c,mi]=t.dataset.createTopic.split(',').map(Number);createTopic(c,mi)}});$('.library-filters').addEventListener('click',e=>{const button=e.target.closest('[data-tree-filter]');if(!button)return;treeFilter=button.dataset.treeFilter;$$('[data-tree-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));tree()});$('#fields').addEventListener('input',markFormDirty);$('#fields').addEventListener('change',markFormDirty);$('#fields').addEventListener('click',builderAction);$('#newCourse').onclick=createCourse;$('#recordForm').onsubmit=apply;$('#previewBtn').onclick=preview;$('#duplicateBtn').onclick=duplicate;$('#deleteBtn').onclick=remove;$('#undoBtn').onclick=undoDelete;$('#moveUp').onclick=()=>move(-1);$('#moveDown').onclick=()=>move(1);$('#adminTheme').onclick=toggleTheme;$('#saveLibrary').onclick=save;$('#exportBtn').onclick=exportFile;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>importFile(e.target.files[0]);$('#treeSearch').oninput=tree;window.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}else if(e.key==='/'&&!typing){e.preventDefault();$('#treeSearch').focus()}else if(e.key==='Escape'&&document.activeElement===$('#treeSearch')){$('#treeSearch').value='';tree();$('#treeSearch').blur()}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}})}catch(error){console.error(error);document.body.insertAdjacentHTML('afterbegin',`<div class="fatal-admin" role="alert"><strong>Admin could not start.</strong><span>${esc(error.message)}</span><button type="button" onclick="localStorage.removeItem('${KEY}');location.reload()">Clear old editor data and reload</button></div>`)}}
document.addEventListener('click',e=>{const menu=$('.backup-menu');if(!menu)return;if(menu.open&&!menu.contains(e.target))menu.open=false;if(e.target.closest('#importBtn,#exportBtn'))menu.open=false});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const menu=$('.backup-menu');if(menu?.open){menu.open=false;menu.querySelector('summary')?.focus()}}});
function loadRemote(){if(!window.PortfolioAPI)return;window.PortfolioAPI.getAcademyLibrary().then(remote=>{if(dirty||libraryDirty)return;const localTime=Date.parse(stored?.savedAt||0)||0,remoteTime=Date.parse(remote?.updatedAt||0)||0;if(stored?.draft&&(!remoteTime||localTime>remoteTime)&&Array.isArray(stored?.courses)){libraryDirty=true;setSync('draft','Local draft newer');$('#saveState').textContent='Local draft recovered · not published';toast('Your newer local draft was recovered');return}setSync('synced',remote?.courses?.length?'Cloud connected':'Cloud ready');if(!Array.isArray(remote?.courses)||!remote.courses.length)return;courses=remote.courses.map(normalizeCourse);stored={version:1,savedAt:remote.updatedAt||new Date().toISOString(),draft:false,courses};localStorage.setItem(KEY,JSON.stringify(stored));selected={type:'course',c:0};tree();form();toast('Latest cloud library loaded')}).catch(error=>{setSync('offline','Offline · local draft');console.warn('Academy library sync unavailable. Using local content.',error)})}
function startAdmin(session){document.body.classList.remove('admin-locked');$('#adminGate').hidden=true;boot();setupEnhancedTools();if(stored?.draft){setSync('draft','Local draft recovered');$('#saveState').textContent='Local draft recovered · not published'}else if(session?.email)setSync('synced',`Signed in · ${session.email}`);loadRemote()}
async function authorizeAdmin(){const api=window.PortfolioAPI,signIn=$('#adminSignIn'),status=$('#gateStatus'),returnTo=location.origin+location.pathname;signIn.href=`${api?.baseUrl||''}/admin/session?return=${encodeURIComponent(returnTo)}`;if(!api){status.textContent='Secure service unavailable.';return}try{const session=await api.getAdminSession();if(session?.authenticated){startAdmin(session);return}status.textContent='Sign in to continue.'}catch(error){status.textContent='Your session is locked. Sign in to continue.';console.info('Admin session required.',error)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',authorizeAdmin);else authorizeAdmin();
})();
