(()=>{'use strict';
const KEY='academy-os-content-v1',clone=v=>JSON.parse(JSON.stringify(v)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),slug=v=>String(v||'record').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
let stored;try{stored=JSON.parse(localStorage.getItem(KEY))}catch{}let courses=stored?.version===1&&Array.isArray(stored.courses)?stored.courses:clone(window.ACADEMY_COURSES),selected=null,dirty=false,libraryDirty=false,undo=null;
function normalizeCourse(course,index){const c={...course,id:course?.id||`course-${index+1}`,slug:course?.slug||course?.id||`course-${index+1}`,title:course?.title||`Untitled course ${index+1}`,summary:course?.summary||'',level:course?.level||'Beginner',skills:Array.isArray(course?.skills)?course.skills:[],published:course?.published!==false,modules:Array.isArray(course?.modules)?course.modules:[]};c.modules=c.modules.map((module,mi)=>({...module,id:module?.id||`module-${mi+1}`,title:module?.title||`Untitled module ${mi+1}`,description:module?.description||'',topics:(Array.isArray(module?.topics)?module.topics:[]).map((topic,ti)=>({...topic,id:topic?.id||`${c.id}-topic-${ti+1}`,title:topic?.title||`Untitled topic ${ti+1}`,time:topic?.time||'20 min',skills:Array.isArray(topic?.skills)?topic.skills:[],objectives:Array.isArray(topic?.objectives)?topic.objectives:[],prerequisites:Array.isArray(topic?.prerequisites)?topic.prerequisites:[],blocks:Array.isArray(topic?.blocks)?topic.blocks:[],practical:topic?.practical&&typeof topic.practical==='object'?topic.practical:{title:'Practical task',steps:[],required:true},quiz:topic?.quiz&&typeof topic.quiz==='object'?topic.quiz:{passingScore:70,questions:[]}}))}));return c}
courses=(Array.isArray(courses)?courses:[]).map(normalizeCourse);if(!courses.length)courses=clone(window.ACADEMY_COURSES||[]).map(normalizeCourse);
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)],topics=()=>courses.flatMap(c=>c.modules.flatMap(m=>m.topics));
function item(){if(!selected)return null;if(selected.type==='course')return courses[selected.c]||null;if(selected.type==='module')return courses[selected.c]?.modules[selected.m]||null;if(selected.type==='topic')return courses[selected.c]?.modules[selected.m]?.topics[selected.t]||null;return null}
const input=(id,label,value='',wide=false,help='')=>`<label class="field ${wide?'wide':''}"><span>${label}</span><input id="${id}" value="${esc(value)}">${help?`<small>${help}</small>`:''}</label>`,area=(id,label,value='',cls='')=>`<label class="field wide"><span>${label}</span><textarea id="${id}" class="${cls}">${esc(value)}</textarea></label>`;
function stats(){const modules=courses.reduce((n,c)=>n+c.modules.length,0),ts=topics().length,published=courses.filter(c=>c.published!==false).length;$('#adminStats').innerHTML=[['COURSES',courses.length],['PUBLISHED',published],['MODULES',modules],['TOPICS',ts]].map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');$('#recordCount').textContent=`${courses.length+modules+ts} records`}
function tree(){const q=$('#treeSearch').value.trim().toLowerCase();$('#adminTree').innerHTML=courses.map((c,ci)=>{const text=[c.title,...c.modules.flatMap(m=>[m.title,...m.topics.map(t=>t.title)])].join(' ').toLowerCase();if(q&&!text.includes(q))return'';return`<section class="tree-course"><button class="tree-record ${selected?.type==='course'&&selected.c===ci?'active':''}" data-select="course,${ci}" type="button"><small>COURSE · ${c.published===false?'DRAFT':'PUBLISHED'}</small><strong>${esc(c.title)}</strong></button><button class="tree-add" data-create-module="${ci}" type="button">+ Add module</button><div class="tree-nested">${c.modules.map((m,mi)=>`<div><button class="tree-record ${selected?.type==='module'&&selected.c===ci&&selected.m===mi?'active':''}" data-select="module,${ci},${mi}" type="button"><small>MODULE ${mi+1}</small><strong>${esc(m.title)}</strong></button><button class="tree-add" data-create-topic="${ci},${mi}" type="button">+ Add topic</button><div class="tree-nested">${m.topics.map((t,ti)=>`<button class="tree-record ${selected?.type==='topic'&&selected.c===ci&&selected.m===mi&&selected.t===ti?'active':''}" data-select="topic,${ci},${mi},${ti}" type="button"><small>TOPIC ${ti+1}</small><strong>${esc(t.title)}</strong></button>`).join('')}</div></div>`).join('')}</div></section>`}).join('')||'<p>No matching content.</p>';stats()}
function select(next){if(dirty&&!confirm('Discard unapplied changes in the open form?'))return;selected=next;dirty=false;tree();form()}
function form(){const x=item();if(!x){$('#recordForm').hidden=true;$('#welcome').hidden=false;health();return}$('#welcome').hidden=true;$('#recordForm').hidden=false;$('#kindLabel').textContent=selected.type.toUpperCase();$('#formTitle').textContent=x.title;$('#errors').hidden=true;
 let html;if(selected.type==='course')html=`<div class="grid">${input('title','Course title',x.title)}${input('id','Course slug',x.slug||x.id)}${input('level','Level',x.level||'Beginner')}${input('skills','Skill tags',(x.skills||[]).join(', '))}${area('summary','Description',x.summary||'')}<label class="toggle field wide"><input id="published" type="checkbox" ${x.published===false?'':'checked'}><span>Published</span></label></div>`;
 if(selected.type==='module')html=`<div class="grid">${input('title','Module title',x.title)}${input('id','Module ID',x.id)}${area('description','Description',x.description||'')}</div>`;
 if(selected.type==='topic')html=`<div class="grid">${input('title','Topic title',x.title)}${input('id','Topic ID',x.id)}${input('time','Estimated time',x.time||'20 min')}${input('skills','Skill tags',(x.skills||[]).join(', '))}${area('objectives','Learning objectives — one per line',(x.objectives||[]).join('\n'))}${area('prerequisites','Required prerequisite topic IDs — one per line',(x.prerequisites||[]).filter(p=>p.type==='required').map(p=>p.topicId).join('\n'))}<section class="section"><h3>Learning content</h3><p>Structured blocks: paragraph, definition, ordered-list, command, scenario, warning, tip, or example.</p>${area('blocks','Content blocks JSON',JSON.stringify(x.blocks||[],null,2),'json')}</section><section class="section"><h3>Practical activity</h3>${area('practical','Practical task JSON',JSON.stringify(x.practical||{title:'Practical task',steps:[],required:true},null,2),'json')}</section><section class="section"><h3>Assessment</h3>${area('quiz','Quiz JSON',JSON.stringify(x.quiz||{passingScore:70,questions:[]},null,2),'json')}</section></div>`;
 $('#fields').innerHTML=html;const {list,index}=collection();$('#moveUp').disabled=index===0;$('#moveDown').disabled=index===list.length-1;$$('#fields input,#fields textarea').forEach(el=>el.addEventListener('input',()=>{dirty=true;$('#saveState').textContent='Unapplied form changes'}));health()}
function parse(id,name,errors){try{return JSON.parse($('#'+id).value)}catch{errors.push(`${name} contains invalid JSON.`);return null}}
function apply(e){e?.preventDefault();const x=item(),errors=[],title=$('#title').value.trim();if(!title)errors.push('Title is required.');
 if(selected.type==='course'){const id=slug($('#id').value);if(courses.some((c,i)=>i!==selected.c&&c.id===id))errors.push('Course slug must be unique.');if(!errors.length)Object.assign(x,{title,id,slug:id,level:$('#level').value.trim(),skills:csv($('#skills').value),summary:$('#summary').value.trim(),published:$('#published').checked})}
 if(selected.type==='module'){const id=slug($('#id').value);if(courses[selected.c].modules.some((m,i)=>i!==selected.m&&m.id===id))errors.push('Module ID must be unique in its course.');if(!errors.length)Object.assign(x,{title,id,description:$('#description').value.trim()})}
 if(selected.type==='topic'){const id=slug($('#id').value),blocks=parse('blocks','Content blocks',errors),practical=parse('practical','Practical task',errors),quiz=parse('quiz','Quiz',errors);if(topics().some(t=>t!==x&&t.id===id))errors.push('Topic ID must be unique.');const prerequisites=lines($('#prerequisites').value).map(topicId=>({topicId,type:'required'}));prerequisites.forEach(p=>{if(!topics().some(t=>t.id===p.topicId))errors.push(`Prerequisite "${p.topicId}" does not exist.`);if(p.topicId===id)errors.push('A topic cannot require itself.')});if(!errors.length)Object.assign(x,{title,id,time:$('#time').value.trim(),skills:csv($('#skills').value),objectives:lines($('#objectives').value),prerequisites,blocks,practical,quiz})}
 if(errors.length)return showErrors(errors);dirty=false;libraryDirty=true;$('#saveState').textContent='Record updated — save library to persist';tree();form();toast('Record updated.');return true}
const csv=v=>v.split(',').map(x=>x.trim()).filter(Boolean),lines=v=>v.split('\n').map(x=>x.trim()).filter(Boolean);
function showErrors(list){const el=$('#errors');el.hidden=false;el.innerHTML=`<strong>Fix these problems:</strong><ul>${list.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;el.focus();return false}
function collection(){if(selected.type==='course')return{list:courses,index:selected.c};if(selected.type==='module')return{list:courses[selected.c].modules,index:selected.m};return{list:courses[selected.c].modules[selected.m].topics,index:selected.t}}
function createCourse(){const n=courses.length+1,id=`course-${n}`;courses.push({id,slug:id,title:`New course ${n}`,level:'Beginner',summary:'',skills:[],published:false,completionRules:{requiredTopicCompletion:100,finalAssessmentScore:70},modules:[]});persistDirty();select({type:'course',c:courses.length-1})}
function createModule(c){const a=courses[c].modules,n=a.length+1;a.push({id:`module-${n}`,title:`New module ${n}`,description:'',topics:[]});persistDirty();select({type:'module',c,m:a.length-1})}
function createTopic(c,m){const a=courses[c].modules[m].topics,n=a.length+1;a.push({id:`${courses[c].id}-topic-${n}`,title:`New topic ${n}`,time:'20 min',skills:[],prerequisites:[],objectives:[],blocks:[],practical:{title:'Practical task',steps:[],required:true},quiz:{passingScore:70,questions:[]}});persistDirty();select({type:'topic',c,m,t:a.length-1})}
function duplicate(){if(dirty&&!apply())return;const {list,index}=collection(),copy=clone(item());copy.title+=' copy';if(selected.type==='course'){copy.id=copy.slug=slug(copy.id+'-copy-'+Date.now().toString().slice(-4));copy.published=false}else if(selected.type==='module')copy.id=slug(copy.id+'-copy-'+Date.now().toString().slice(-4));else{copy.id=slug(copy.id+'-copy-'+Date.now().toString().slice(-4));copy.prerequisites=[]}list.splice(index+1,0,copy);persistDirty();const n={...selected};if(n.type==='course')n.c++;else if(n.type==='module')n.m++;else n.t++;select(n);toast('Record duplicated.')}
function remove(){const x=item();if(selected.type==='course'&&courses.length===1)return toast('Create another course before deleting the final course.');if(!confirm(`Delete "${x.title}"?`))return;const {list,index}=collection();undo={item:clone(x),selected:{...selected},index};list.splice(index,1);selected=null;dirty=false;$('#undoBtn').hidden=false;persistDirty();tree();form();toast('Deleted. You can undo before saving.')}
function undoDelete(){if(!undo)return;const p=undo.selected;let list=p.type==='course'?courses:p.type==='module'?courses[p.c]?.modules:courses[p.c]?.modules[p.m]?.topics;if(!list)return toast('Parent record no longer exists.');list.splice(Math.min(undo.index,list.length),0,undo.item);selected={...p};if(p.type==='course')selected.c=Math.min(undo.index,list.length-1);if(p.type==='module')selected.m=Math.min(undo.index,list.length-1);if(p.type==='topic')selected.t=Math.min(undo.index,list.length-1);undo=null;$('#undoBtn').hidden=true;persistDirty();tree();form();toast('Deletion undone.')}
function move(d){if(dirty&&!apply())return;const {list,index}=collection(),to=index+d;if(to<0||to>=list.length)return;[list[index],list[to]]=[list[to],list[index]];if(selected.type==='course')selected.c=to;else if(selected.type==='module')selected.m=to;else selected.t=to;persistDirty();tree();form()}
function persistDirty(){libraryDirty=true;$('#saveState').textContent='Library has unsaved changes'}
function validate(){const errors=[];if(!courses.length)errors.push('At least one course is required.');const ids=new Set();topics().forEach(t=>{if(ids.has(t.id))errors.push(`Duplicate topic ID: ${t.id}`);ids.add(t.id)});topics().forEach(t=>(t.prerequisites||[]).forEach(p=>{if(!ids.has(p.topicId))errors.push(`${t.title} has missing prerequisite ${p.topicId}.`)}));courses.filter(c=>c.published!==false).forEach(c=>{if(!c.modules.length)errors.push(`Published course "${c.title}" has no modules.`);c.modules.forEach(m=>{if(!m.topics.length)errors.push(`Published module "${m.title}" has no topics.`)})});return errors}
function save(){if(dirty&&!apply())return;const errors=validate();if(errors.length){if(item())showErrors(errors);else toast(errors[0]);return}try{localStorage.setItem(KEY,JSON.stringify({version:1,savedAt:new Date().toISOString(),courses}));undo=null;libraryDirty=false;$('#undoBtn').hidden=true;$('#saveState').textContent='Library saved';toast('Course library saved. Reload learner view to use changes.')}catch{toast('Save failed: browser storage is unavailable. Export a JSON backup instead.')}}
function health(){const x=item();if(!x){$('#health').innerHTML='<p>Select a record to see validation and completeness.</p>';return}const checks=selected.type==='course'?[['Title',x.title],['Description',x.summary],['Skills',x.skills?.length],['Modules',x.modules?.length]]:selected.type==='module'?[['Title',x.title],['Description',x.description],['Topics',x.topics?.length]]:[['Title',x.title],['Objectives',x.objectives?.length],['Content blocks',x.blocks?.length],['Practical task',x.practical?.title],['Questions',x.quiz?.questions?.length]],score=Math.round(checks.filter(c=>c[1]).length/checks.length*100);$('#health').innerHTML=`<div class="health-card"><strong>${score}%</strong><p>Content completeness</p><ul>${checks.map(c=>`<li class="${c[1]?'':'bad'}"><span>${c[0]}</span><b>${c[1]?'Ready':'Missing'}</b></li>`).join('')}</ul></div>`}
function exportFile(){const b=new Blob([JSON.stringify({schema:'academy-os-content',version:1,exportedAt:new Date().toISOString(),courses},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='academy-os-content.json';a.click();URL.revokeObjectURL(u)}
async function importFile(f){try{const d=JSON.parse(await f.text());if(d.schema!=='academy-os-content'||!d.courses?.length)throw Error();courses=clone(d.courses);selected=null;dirty=false;libraryDirty=true;tree();form();toast('Imported. Save library to persist.')}catch{toast('Import failed: invalid Academy OS file.')}}
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2500)}
function boot(){try{tree();form();$('#adminTree').addEventListener('click',e=>{const s=e.target.closest('[data-select]'),m=e.target.closest('[data-create-module]'),t=e.target.closest('[data-create-topic]');if(s){const [type,c,mi,ti]=s.dataset.select.split(',');select({type,c:+c,m:mi===undefined?undefined:+mi,t:ti===undefined?undefined:+ti})}else if(m)createModule(+m.dataset.createModule);else if(t){const [c,mi]=t.dataset.createTopic.split(',').map(Number);createTopic(c,mi)}});$('#newCourse').onclick=createCourse;$('#recordForm').onsubmit=apply;$('#duplicateBtn').onclick=duplicate;$('#deleteBtn').onclick=remove;$('#undoBtn').onclick=undoDelete;$('#moveUp').onclick=()=>move(-1);$('#moveDown').onclick=()=>move(1);$('#saveLibrary').onclick=save;$('#exportBtn').onclick=exportFile;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>importFile(e.target.files[0]);$('#treeSearch').oninput=tree;window.addEventListener('beforeunload',e=>{if(dirty||libraryDirty){e.preventDefault();e.returnValue=''}})}catch(error){console.error(error);document.body.insertAdjacentHTML('afterbegin',`<div class="fatal-admin" role="alert"><strong>Admin could not start.</strong><span>${esc(error.message)}</span><button type="button" onclick="localStorage.removeItem('${KEY}');location.reload()">Clear old editor data and reload</button></div>`)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
