(() => {
  'use strict';
  const meta = document.querySelector('meta[name="portfolio-api-base"]');
  const baseUrl = (meta?.content || 'https://portfolio-api.m-arslanrafaqat.workers.dev').replace(/\/$/, '');
  const DEVICE_KEY = 'ma-portfolio-device-id-v1', timers = new Map();
  function deviceId(){try{let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_KEY,id)}return id}catch{return null}}
  async function request(path,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),options.timeout||8000);try{const response=await fetch(baseUrl+path,{method:options.method||'GET',credentials:'include',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...options.headers},body:options.body?JSON.stringify(options.body):undefined,signal:controller.signal});if(response.status===404)return null;if(!response.ok)throw new Error(`API ${response.status}`);return response.status===204?null:response.json()}finally{clearTimeout(timeout)}}
  function queue(key,task,delay=700){clearTimeout(timers.get(key));timers.set(key,setTimeout(async()=>{timers.delete(key);try{await task();window.dispatchEvent(new CustomEvent('portfolio-api-status',{detail:{key,state:'synced'}}))}catch(error){console.warn(`Backend sync unavailable for ${key}. Local data is safe.`,error);window.dispatchEvent(new CustomEvent('portfolio-api-status',{detail:{key,state:'offline'}}))}},delay))}
  window.PortfolioAPI=Object.freeze({baseUrl,deviceId,request,queue,getAdminSession:()=>request('/admin/session'),getAcademyProgress:()=>request(`/academy/progress/${encodeURIComponent(deviceId()||'anonymous')}`),saveAcademyProgress:progress=>request(`/academy/progress/${encodeURIComponent(deviceId()||'anonymous')}`,{method:'PUT',body:{progress}}),getAcademyLibrary:()=>request('/academy/library'),saveAcademyLibrary:courses=>request('/admin/library',{method:'PUT',body:{version:1,courses}}),getResumeDraft:()=>request(`/resume/draft/${encodeURIComponent(deviceId()||'anonymous')}`),saveResumeDraft:draft=>request(`/resume/draft/${encodeURIComponent(deviceId()||'anonymous')}`,{method:'PUT',body:{draft}})});
})();
