(() => {
  'use strict';
  const STORAGE_KEY = 'ma-resume-builder-v1';
  const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const sectionLabels = { summary:'Professional Summary', experience:'Experience', education:'Education', skills:'Skills', certification:'Certifications', project:'Projects', language:'Languages', custom:'Additional Information' };
  const defaultOrder = Object.keys(sectionLabels);
  const lists = { experience:'experienceList', education:'educationList', certification:'certificationList', project:'projectList', language:'languageList' };
  const form = document.querySelector('#builderForm');
  const preview = document.querySelector('#resumePreview');
  const sectionsRoot = document.querySelector('#resumeSections');
  const saveState = document.querySelector('#saveState');
  let photoData = '', hiddenSections = [], manualZoom = null, saveTimer;

  const escapeHTML = v => String(v || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const value = name => form.elements[name]?.value.trim() || '';
  const lines = raw => String(raw || '').split(/\n+/).map(x => x.replace(/^[•\-*]\s*/, '').trim()).filter(Boolean);
  const validUrl = raw => { if (!raw) return true; try { return ['http:','https:'].includes(new URL(raw).protocol); } catch { return false; } };
  const linkLabel = raw => { try { const u = new URL(raw); return u.hostname.replace(/^www\./,'') + u.pathname.replace(/\/$/,''); } catch { return raw; } };
  const safeLink = raw => validUrl(raw) && raw ? `<a href="${escapeHTML(raw)}">${escapeHTML(linkLabel(raw))}</a>` : '';

  function toast(message) { const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2600); }
  function populateDates(card) {
    card.querySelectorAll('[data-field$="Month"]').forEach(s=>s.innerHTML='<option value="">Month</option>'+MONTHS.map((m,i)=>`<option value="${i+1}">${m}</option>`).join(''));
    const now=new Date().getFullYear();card.querySelectorAll('[data-field$="Year"]').forEach(s=>s.innerHTML='<option value="">Year</option>'+Array.from({length:72},(_,i)=>now+1-i).map(y=>`<option>${y}</option>`).join(''));
  }
  function migrateDate(data,prefix){if(!data||data[`${prefix}Month`]||!data[prefix])return;const m=String(data[prefix]).match(/^(\d{4})-(\d{2})/);if(m){data[`${prefix}Year`]=m[1];data[`${prefix}Month`]=String(Number(m[2]));}}
  function addItem(type,raw={}) {
    const data={...raw};if(type==='experience'){migrateDate(data,'start');migrateDate(data,'end');}if(type==='education'||type==='certification')migrateDate(data,'date');
    const card=document.querySelector(`#${type}Template`).content.firstElementChild.cloneNode(true);populateDates(card);
    card.querySelectorAll('[data-field]').forEach(f=>{const k=f.dataset.field;f.type==='checkbox'?f.checked=Boolean(data[k]):f.value=data[k]||'';});
    document.querySelector(`#${lists[type]}`).append(card);wireCurrent(card);renumber(type);return card;
  }
  function wireCurrent(card){const current=card.querySelector('[data-field="current"]');if(!current)return;const ends=['endMonth','endYear'].map(k=>card.querySelector(`[data-field="${k}"]`));const sync=()=>ends.forEach(el=>{el.disabled=current.checked;el.required=!current.checked;if(current.checked)el.value='';});current.addEventListener('change',sync);sync();}
  function renumber(type){document.querySelectorAll(`[data-type="${type}"] .item-number`).forEach((el,i)=>el.textContent=String(i+1).padStart(2,'0'));}
  function collectCard(card){const item={};card.querySelectorAll('[data-field]').forEach(f=>item[f.dataset.field]=f.type==='checkbox'?f.checked:f.value.trim());return item;}
  const collectItems=type=>[...document.querySelectorAll(`[data-type="${type}"]`)].map(collectCard);
  function updateCardTitles(){document.querySelectorAll('.repeat-card').forEach(card=>{const item=collectCard(card),type=card.dataset.type;let title='New entry';if(type==='experience')title=[item.role||'New experience',item.company].filter(Boolean).join(' — ');if(type==='education')title=[item.degree||'New education',item.institution].filter(Boolean).join(' — ');if(type==='certification')title=item.name||'New certification';if(type==='project')title=item.name||'New project';if(type==='language')title=item.name||'New language';const number=card.querySelector('.item-number')?.textContent||'';card.querySelector('.card-head strong').innerHTML=`${escapeHTML(title)} <b class="item-number">${number}</b>`;const complete=type==='experience'?item.role&&item.company&&item.startMonth&&item.startYear&&(item.current||(item.endMonth&&item.endYear)):type==='education'?item.degree&&item.institution&&item.dateMonth&&item.dateYear:type==='certification'||type==='project'||type==='language'?item.name:true;card.classList.toggle('entry-complete',Boolean(complete));});}
  function focusNewCard(card){const section=card.closest('details');if(section)section.open=true;requestAnimationFrame(()=>{card.scrollIntoView({behavior:'smooth',block:'center'});card.querySelector('input:not([type="checkbox"]),select,textarea')?.focus({preventScroll:true});});}
  const getOrder=()=>[...document.querySelectorAll('#sectionOrder li')].map(li=>li.dataset.section);
  function collectData(){const fields={};[...form.elements].forEach(el=>{if(el.name&&!['photo','accent'].includes(el.name))fields[el.name]=el.type==='checkbox'?el.checked:el.value;});return{version:2,fields,photoData,hiddenSections,pageSize:document.querySelector('#pageSize').value,density:document.querySelector('#density').value,template:document.querySelector('#templateStyle').value,accent:document.querySelector('[name="accent"]:checked').value,uiTheme:document.body.dataset.uiTheme||'dark',order:getOrder(),items:Object.fromEntries(Object.keys(lists).map(t=>[t,collectItems(t)]))};}
  function resetLists(){Object.values(lists).forEach(id=>document.querySelector(`#${id}`).innerHTML='');}
  function applyData(data){
    resetLists();[...form.elements].forEach(el=>{if(el.name&&!['photo','accent'].includes(el.name))el.type==='checkbox'?el.checked=false:el.value='';});
    Object.entries(data.fields||{}).forEach(([n,v])=>{const el=form.elements[n];if(el)el.type==='checkbox'?el.checked=Boolean(v):el.value=v;});if(form.elements.summary.value.length>2000)form.elements.summary.value=form.elements.summary.value.slice(0,2000);photoData=data.photoData||'';hiddenSections=Array.isArray(data.hiddenSections)?data.hiddenSections.filter(x=>defaultOrder.includes(x)):[];
    document.querySelector('#pageSize').value=data.pageSize||'a4';document.querySelector('#density').value=data.density||'standard';document.querySelector('#templateStyle').value=data.template||'modern';const accent=document.querySelector(`[name="accent"][value="${data.accent||'navy'}"]`);if(accent)accent.checked=true;setTheme(data.uiTheme||'dark',false);
    Object.keys(lists).forEach(t=>(data.items?.[t]||[]).forEach(item=>addItem(t,item)));Object.keys(lists).forEach(t=>{if(!document.querySelector(`[data-type="${t}"]`))addItem(t);});buildOrder(data.order||defaultOrder);render();
  }
  function restore(){let data;try{data=JSON.parse(localStorage.getItem(STORAGE_KEY));}catch{data=null;}applyData(data||{items:{},order:defaultOrder,template:'modern',uiTheme:'dark'});}
  function buildOrder(order){const root=document.querySelector('#sectionOrder');root.innerHTML='';[...order,...defaultOrder.filter(x=>!order.includes(x))].forEach(key=>{const li=document.createElement('li');li.dataset.section=key;li.innerHTML=`<label class="visibility-toggle"><input type="checkbox" data-visible="${key}" ${hiddenSections.includes(key)?'':'checked'}><span aria-hidden="true"></span><b>${sectionLabels[key]}</b></label><div><button type="button" data-move="up" aria-label="Move ${sectionLabels[key]} up">↑</button><button type="button" data-move="down" aria-label="Move ${sectionLabels[key]} down">↓</button></div>`;root.append(li);});}
  function save(immediate=false){clearTimeout(saveTimer);saveState.textContent='SAVING…';const run=()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(collectData()));saveState.textContent='SAVED LOCALLY';}catch{saveState.textContent='STORAGE FULL';}};immediate?run():saveTimer=setTimeout(run,300);}
  function setTheme(theme,shouldSave=true){const mode=theme==='light'?'light':'dark';document.body.dataset.uiTheme=mode;const b=document.querySelector('#themeMode');b.textContent=mode==='dark'?'☀':'☾';b.setAttribute('aria-label',`Switch to ${mode==='dark'?'light':'dark'} theme`);if(shouldSave)save();}
  function dateLabel(item,prefix){if(item[`${prefix}Month`]&&item[`${prefix}Year`])return`${MONTHS[Number(item[`${prefix}Month`])-1]} ${item[`${prefix}Year`]}`;if(item[prefix]){const[y,m]=item[prefix].split('-');return m&&y?`${MONTHS[Number(m)-1]} ${y}`:'';}return'';}
  function renderContact(){const parts=[];if(value('email'))parts.push(`<a href="mailto:${escapeHTML(value('email'))}">${escapeHTML(value('email'))}</a>`);if(value('phone'))parts.push(`<a href="tel:${escapeHTML(value('phone').replace(/\s/g,''))}">${escapeHTML(value('phone'))}</a>`);if(value('whatsapp'))parts.push(`<a href="https://wa.me/${escapeHTML(value('whatsapp').replace(/\D/g,''))}">WhatsApp: ${escapeHTML(value('whatsapp'))}</a>`);const location=[value('address'),value('city'),value('country')].filter(Boolean).join(', ');if(location)parts.push(`<span>${escapeHTML(location)}</span>`);['linkedin','github','portfolio'].forEach(k=>{const link=safeLink(value(k));if(link)parts.push(link);});document.querySelector('#pContact').innerHTML=parts.join('');}
  const section=(key,body)=>body?`<section class="resume-section" data-section="${key}"><h2>${escapeHTML(key==='custom'&&value('customTitle')?value('customTitle'):sectionLabels[key])}</h2>${body}</section>`:'';
  const titleLine=(title,date='')=>`<div class="item-title-line"><h3>${escapeHTML(title)}</h3>${date?`<time>${escapeHTML(date)}</time>`:''}</div>`;
  function renderSection(key){
    if(hiddenSections.includes(key))return'';if(key==='summary')return section(key,value('summary')?`<p>${escapeHTML(value('summary'))}</p>`:'');if(key==='skills'){const items=value('skills').split(/[,\n]+/).map(x=>x.trim()).filter(Boolean);return section(key,items.length?`<div class="skill-list">${items.map(x=>`<span>${escapeHTML(x)}</span>`).join('')}</div>`:'');}if(key==='custom')return section(key,lines(value('customContent')).map(x=>`<p>${escapeHTML(x)}</p>`).join(''));
    const items=collectItems(key);
    if(key==='experience')return section(key,items.filter(x=>x.role||x.company).map(x=>`<article class="resume-item">${titleLine(x.role||'Role',`${dateLabel(x,'start')}${dateLabel(x,'start')?' - ':''}${x.current?'Present':dateLabel(x,'end')}`)}<p class="item-subtitle">${escapeHTML([x.company,x.location].filter(Boolean).join(' · '))}</p>${x.summary?`<p class="item-summary">${escapeHTML(x.summary)}</p>`:''}${lines(x.bullets).length?`<ul>${lines(x.bullets).map(b=>`<li>${escapeHTML(b)}</li>`).join('')}</ul>`:''}</article>`).join(''));
    if(key==='education')return section(key,items.filter(x=>x.degree||x.institution).map(x=>`<article class="resume-item">${titleLine(x.degree||'Qualification',dateLabel(x,'date'))}<p class="item-subtitle">${escapeHTML([x.institution,x.location].filter(Boolean).join(' · '))}</p>${x.details?`<p>${escapeHTML(x.details)}</p>`:''}</article>`).join(''));
    if(key==='certification')return section(key,items.filter(x=>x.name).map(x=>`<article class="resume-item">${titleLine(x.name,dateLabel(x,'date'))}<p>${escapeHTML(x.issuer)}${x.credentialId?` · Credential ID: ${escapeHTML(x.credentialId)}`:''}${x.url&&validUrl(x.url)?` · ${safeLink(x.url)}`:''}</p></article>`).join(''));
    if(key==='project')return section(key,items.filter(x=>x.name).map(x=>`<article class="resume-item">${titleLine(x.name)}${x.tech?`<p class="item-subtitle">${escapeHTML(x.tech)}</p>`:''}${x.description?`<p>${escapeHTML(x.description)}</p>`:''}<div class="project-links">${[safeLink(x.url),safeLink(x.github)].filter(Boolean).join(' · ')}</div></article>`).join(''));
    if(key==='language')return section(key,items.filter(x=>x.name).length?`<div class="language-grid">${items.filter(x=>x.name).map(x=>`<span><strong>${escapeHTML(x.name)}</strong> - ${escapeHTML(x.level)}</span>`).join('')}</div>`:'');return'';
  }
  function clearFieldErrors(){form.querySelectorAll('.field-error').forEach(el=>el.remove());form.querySelectorAll('.invalid,.entry-invalid').forEach(el=>el.classList.remove('invalid','entry-invalid'));}
  function markField(target,message){if(!target)return;target.classList.add('invalid');const error=document.createElement('span');error.className='field-error';error.textContent=message;target.insertAdjacentElement('afterend',error);target.closest('.repeat-card')?.classList.add('entry-invalid');}
  function dateIndex(item,prefix){return item[`${prefix}Year`]&&item[`${prefix}Month`]?Number(item[`${prefix}Year`])*12+Number(item[`${prefix}Month`]):null;}
  function qualityCheck(){
    clearFieldErrors();const issues=[];
    [['fullName','full name'],['jobTitle','professional title'],['email','email'],['phone','phone'],['summary','summary'],['skills','skills']].forEach(([k,label])=>{if(!value(k)){issues.push(`Add ${label}.`);markField(form.elements[k],`Please add your ${label}.`);}});
    if(value('email')&&!form.elements.email.validity.valid){issues.push('Use a valid email address.');markField(form.elements.email,'Enter a valid email address.');}
    ['linkedin','github','portfolio'].forEach(k=>{if(value(k)&&!validUrl(value(k))){issues.push(`Correct the ${k} URL.`);markField(form.elements[k],'Enter a full URL beginning with https://');}});
    Object.entries(lists).forEach(([type])=>document.querySelectorAll(`[data-type="${type}"]`).forEach((card,i)=>{const item=collectCard(card);['url','github'].forEach(k=>{if(item[k]&&!validUrl(item[k])){issues.push(`Correct the URL in ${sectionLabels[type]} item ${i+1}.`);markField(card.querySelector(`[data-field="${k}"]`),'Enter a full URL beginning with https://');}});if(type==='experience'&&(item.role||item.company)){const startComplete=item.startMonth&&item.startYear,endComplete=item.current||(item.endMonth&&item.endYear);if(!startComplete){issues.push(`Complete the start date for experience ${i+1}.`);markField(card.querySelector('[data-field="startMonth"]').closest('.date-select'),'Choose a start month and year.');}if(!endComplete){issues.push(`Complete the end date for experience ${i+1}.`);markField(card.querySelector('[data-field="endMonth"]').closest('.date-select'),'Choose an end month and year.');}if(startComplete&&!item.current&&endComplete&&dateIndex(item,'end')<dateIndex(item,'start')){issues.push(`Correct the date order for experience ${i+1}.`);markField(card.querySelector('[data-field="endMonth"]').closest('.date-select'),'End date cannot be earlier than start date.');}}if(type==='education'&&(item.degree||item.institution)&&(!item.dateMonth||!item.dateYear)){issues.push(`Add the graduation date for education ${i+1}.`);markField(card.querySelector('[data-field="dateMonth"]').closest('.date-select'),'Choose a graduation month and year.');}}));
    if(value('summary')&&value('summary').split(/\s+/).filter(Boolean).length<25)issues.push('Strengthen the summary to at least 25 words.');if(!collectItems('experience').some(x=>x.role&&x.company))issues.push('Add at least one complete experience entry.');if(!collectItems('education').some(x=>x.degree&&x.institution))issues.push('Add at least one complete education entry.');
    const score=Math.max(0,Math.min(100,100-issues.length*8)),ring=document.querySelector('#scoreRing');document.querySelector('#scoreValue').textContent=score;ring.style.setProperty('--score-angle',`${score*3.6}deg`);ring.classList.remove('score-updated');requestAnimationFrame(()=>ring.classList.add('score-updated'));const panel=document.querySelector('#qualityPanel');panel.className=`quality-panel${issues.length?'':' good'}`;panel.innerHTML=issues.length?`<strong>${issues.length} CHECK${issues.length===1?'':'S'} TO REVIEW</strong><ul>${issues.slice(0,6).map(x=>`<li class="error">${escapeHTML(x)}</li>`).join('')}</ul>${issues.length>6?`<small>+ ${issues.length-6} more</small>`:''}`:'<strong>READY TO EXPORT</strong><br>No basic completeness or formatting issues detected.';return{issues,score};
  }
  function fitPreview(){const stage=document.querySelector('#previewStage'),pane=document.querySelector('#previewPane');if(!stage||!pane||!pane.offsetWidth)return;preview.style.minHeight='';const pageHeight=document.querySelector('#pageSize').value==='letter'?1056:1123;const pages=Math.max(1,Math.ceil((preview.scrollHeight-2)/pageHeight));preview.style.minHeight=`${pages*pageHeight}px`;const fit=Math.min(1,Math.max(.25,(pane.clientWidth-36)/preview.offsetWidth)),scale=manualZoom||fit;preview.style.setProperty('--preview-scale',scale.toFixed(4));stage.style.height=`${Math.ceil(pages*pageHeight*scale)}px`;document.querySelector('#pageGuides').innerHTML=Array.from({length:pages-1},(_,i)=>`<i style="top:${Math.round((i+1)*pageHeight*scale)}px"></i>`).join('');document.querySelector('#pageStatus').textContent=`${pages} PAGE${pages===1?'':'S'}`;document.querySelector('#overflowStatus').textContent=pages>1?'Multi-page resume':'Ready to print';document.querySelector('#zoomValue').textContent=manualZoom?`${Math.round(scale*100)}%`:'FIT';}
  function render(){document.querySelector('#pName').textContent=value('fullName')||'YOUR NAME';document.querySelector('#pTitle').textContent=value('jobTitle')||'PROFESSIONAL TITLE';renderContact();const photo=document.querySelector('#pPhoto');photo.src=photoData||'';photo.classList.toggle('visible',Boolean(photoData&&form.elements.includePhoto.checked));preview.className=`resume-page size-${document.querySelector('#pageSize').value} density-${document.querySelector('#density').value} accent-${document.querySelector('[name="accent"]:checked').value} template-${document.querySelector('#templateStyle').value}`;document.querySelector('#printPageStyle').textContent=`@page{size:${document.querySelector('#pageSize').value==='letter'?'Letter':'A4'};margin:0}`;sectionsRoot.innerHTML=getOrder().map(renderSection).join('');document.querySelector('#summaryCount').textContent=value('summary').length;updateCardTitles();qualityCheck();save();requestAnimationFrame(fitPreview);}
  function demoData(){return{version:3,template:'modern',uiTheme:document.body.dataset.uiTheme||'dark',pageSize:'a4',density:'standard',accent:'blue',order:defaultOrder,hiddenSections:[],fields:{fullName:'Nora Bennett',jobTitle:'Service Desk Analyst',email:'nora.bennett@example.com',phone:'+1 555 010 2486',whatsapp:'',address:'Downtown',city:'Vancouver',country:'Canada',linkedin:'https://example.com/nora-bennett',github:'https://example.com/nora-bennett-labs',portfolio:'https://example.com/nora-bennett-portfolio',summary:'Service Desk Analyst with experience supporting workplace users, Windows devices, cloud accounts and office networks. Known for calm communication, structured troubleshooting and clear documentation that helps teams resolve incidents efficiently and prevent repeat problems.',skills:'Service Desk, Windows 11, Microsoft 365, Entra ID, TCP/IP, DNS, Ticket Management, Remote Support',customTitle:'Community Work',customContent:'Volunteer digital-skills mentor\nPrepared beginner-friendly technology guides'},items:{experience:[{role:'Service Desk Analyst',company:'Northstar Systems',location:'Vancouver, Canada',startMonth:'4',startYear:'2023',current:true,summary:'Provide first- and second-line support for users across a hybrid workplace.',bullets:'Resolved an average of 35 support requests each week\nCreated knowledge articles for recurring account and connectivity issues\nImproved ticket documentation quality through a shared resolution checklist'},{role:'IT Support Assistant',company:'Blue Oak Studio',location:'Victoria, Canada',startMonth:'7',startYear:'2021',endMonth:'3',endYear:'2023',current:false,summary:'Supported employee devices, software access and meeting-room technology.',bullets:'Prepared laptops and accounts for new employees\nReduced repeat printer incidents by documenting setup standards'}],education:[{degree:'Diploma in Information Technology',institution:'Westbridge Technical College',location:'British Columbia, Canada',dateMonth:'6',dateYear:'2021',details:'Graduated with distinction'}],certification:[{name:'IT Service Management Fundamentals',issuer:'Example Learning Institute',dateMonth:'9',dateYear:'2023',credentialId:'DEMO-2023-104'}],project:[{name:'Help Desk Knowledge Base',tech:'HTML, CSS, JavaScript',url:'https://example.com/help-desk-project',github:'https://example.com/help-desk-source',description:'Designed a searchable troubleshooting guide for common workplace technology issues.'}],language:[{name:'English',level:'Native'},{name:'French',level:'Intermediate'}]}};}
  function validateDraft(data){if(!data||typeof data!=='object'||Array.isArray(data)||!data.fields||typeof data.fields!=='object'||Array.isArray(data.fields)||!data.items||typeof data.items!=='object'||Array.isArray(data.items))return false;if(data.order&&!Array.isArray(data.order))return false;if(data.hiddenSections&&!Array.isArray(data.hiddenSections))return false;return Object.keys(lists).every(type=>data.items[type]===undefined||Array.isArray(data.items[type]));}
  function compressPhoto(file){return new Promise((resolve,reject)=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type))return reject(new Error('type'));if(file.size>5_000_000)return reject(new Error('size'));const reader=new FileReader();reader.onerror=()=>reject(new Error('read'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('image'));image.onload=()=>{const scale=Math.min(1,600/image.width,600/image.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82));};image.src=reader.result;};reader.readAsDataURL(file);});}
  function downloadDraft(){save(true);const blob=new Blob([JSON.stringify(collectData(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${(value('fullName')||'resume').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')}-resume-draft.json`;a.click();URL.revokeObjectURL(url);toast('Draft downloaded');}
  document.addEventListener('click',event=>{const more=document.querySelector('.toolbar-more');if(more.open&&!event.target.closest('.toolbar-more'))more.open=false;const add=event.target.closest('[data-add]');if(add){const card=addItem(add.dataset.add);render();focusNewCard(card);toast('New entry added');}const duplicate=event.target.closest('[data-duplicate]');if(duplicate){const source=duplicate.closest('.repeat-card'),card=addItem(source.dataset.type,collectCard(source));render();focusNewCard(card);toast('Entry duplicated');}const remove=event.target.closest('[data-remove]');if(remove){const card=remove.closest('.repeat-card'),type=card.dataset.type;if(!confirm('Remove this entry? This cannot be undone.'))return;card.remove();renumber(type);render();toast('Entry removed');}const move=event.target.closest('[data-move]');if(move){const li=move.closest('li'),sibling=move.dataset.move==='up'?li.previousElementSibling:li.nextElementSibling;if(sibling)li.parentElement.insertBefore(move.dataset.move==='up'?li:sibling,move.dataset.move==='up'?sibling:li);buildOrder(getOrder());render();toast('Section order updated');}});
  form.addEventListener('input',event=>{if(event.target===form.elements.summary&&event.target.value.length>2000)event.target.value=event.target.value.slice(0,2000);render();});form.addEventListener('change',render);document.querySelector('.builder-toolbar').addEventListener('change',render);
  document.querySelector('#sectionOrder').addEventListener('change',event=>{if(!event.target.matches('[data-visible]'))return;const key=event.target.dataset.visible;hiddenSections=event.target.checked?hiddenSections.filter(x=>x!==key):[...new Set([...hiddenSections,key])];render();toast(`${sectionLabels[key]} ${event.target.checked?'shown':'hidden'}`);});
  document.querySelector('#photoInput').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{photoData=await compressPhoto(file);form.elements.includePhoto.checked=true;render();toast('Photo optimized and added');}catch(error){alert(error.message==='type'?'Choose a JPG, PNG or WebP image.':'Choose an image smaller than 5 MB.');}event.target.value='';});
  document.querySelector('#themeMode').addEventListener('click',()=>setTheme(document.body.dataset.uiTheme==='dark'?'light':'dark'));
  document.querySelector('#mobileViewToggle').addEventListener('click',event=>{const active=document.querySelector('#workspace').classList.toggle('show-preview');event.currentTarget.textContent=active?'Edit':'Preview';event.currentTarget.setAttribute('aria-pressed',String(active));requestAnimationFrame(()=>{fitPreview();document.querySelector(active?'#previewPane':'#builderForm').scrollIntoView({block:'start'});});});
  document.querySelector('#zoomIn').addEventListener('click',()=>{manualZoom=Math.min(1.2,(manualZoom||parseFloat(getComputedStyle(preview).getPropertyValue('--preview-scale'))||.8)+.1);fitPreview();});document.querySelector('#zoomOut').addEventListener('click',()=>{manualZoom=Math.max(.3,(manualZoom||parseFloat(getComputedStyle(preview).getPropertyValue('--preview-scale'))||.8)-.1);fitPreview();});
  document.querySelector('#loadDemo').addEventListener('click',()=>{if(!confirm('Load professional sample data? Your current draft will be replaced.'))return;applyData(demoData());save(true);toast('Sample resume loaded');});document.querySelector('#exportDraft').addEventListener('click',downloadDraft);
  document.querySelector('#importDraft').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(file.size>2_000_000){alert('Draft file is too large. Choose a JSON file smaller than 2 MB.');event.target.value='';return;}const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!validateDraft(data))throw new Error();if(!confirm('Import this draft? Your current resume will be replaced.')){event.target.value='';return;}applyData(data);save(true);toast('Draft imported successfully');}catch{alert('This file is not a valid Resume Builder draft. Your current resume was not changed.');}event.target.value='';};reader.readAsText(file);});
  document.querySelector('#clearDraft').addEventListener('click',()=>{if(!confirm('Clear all resume data saved in this browser?'))return;const uiTheme=document.body.dataset.uiTheme||'dark';applyData({version:3,uiTheme,template:'modern',pageSize:'a4',density:'standard',accent:'navy',order:defaultOrder,hiddenSections:[],fields:{},items:Object.fromEntries(Object.keys(lists).map(type=>[type,[]]))});save(true);document.querySelector('.toolbar-more').open=false;toast('Resume cleared');});
  document.querySelector('#printResume').addEventListener('click',()=>{const{issues}=qualityCheck();if(issues.some(x=>/valid|Correct|dates/.test(x))&&!confirm('Some validation checks still need attention. Export anyway?'))return;document.querySelector('#exportDialog').showModal();});document.querySelector('#exportDialog').addEventListener('close',event=>{if(event.target.returnValue==='print'){const originalTitle=document.title,name=(value('fullName')||'Professional').replace(/\s+/g,' ').trim();document.title=`${name} Resume`;window.addEventListener('afterprint',()=>{document.title=originalTitle;},{once:true});window.print();}});
  document.querySelector('.mobile-action-bar').addEventListener('click',event=>{const button=event.target.closest('[data-mobile-action]'),action=button?.dataset.mobileAction;if(!action)return;const buttons=document.querySelectorAll('[data-mobile-action="edit"],[data-mobile-action="preview"]');if(action==='edit'||action==='preview')buttons.forEach(item=>{const active=item.dataset.mobileAction===action;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active));});if(action==='edit'){document.querySelector('#workspace').classList.remove('show-preview');requestAnimationFrame(()=>document.querySelector('#builderForm').scrollIntoView({block:'start'}));}if(action==='preview'){document.querySelector('#workspace').classList.add('show-preview');requestAnimationFrame(()=>{fitPreview();document.querySelector('#previewPane').scrollIntoView({block:'start'});});}if(action==='save'){save(true);toast('Draft saved in this browser');}if(action==='export')document.querySelector('#printResume').click();});
  window.addEventListener('resize',fitPreview);window.addEventListener('beforeprint',()=>{preview.style.minHeight='';});window.addEventListener('afterprint',fitPreview);if('ResizeObserver'in window)new ResizeObserver(fitPreview).observe(document.querySelector('#previewPane'));restore();
})();
