const {chromium}=require('playwright');
const lib=require('../vendor/pdf-tools/pdf-lib.min.js');
const fs=require('fs');
const assert=require('assert/strict');
const out=require('path').resolve('test-results'); fs.mkdirSync(out,{recursive:true});
(async()=>{
 const doc=await lib.PDFDocument.create();
 const titles=['APPLICATION PACKAGE','EXPERIENCE & IMPACT','TECHNICAL SKILLS','PROJECT HIGHLIGHTS','CERTIFICATIONS','SUPPORTING DOCUMENTS','REFERENCES','THANK YOU'];
 for(let i=0;i<8;i++){const p=doc.addPage(i===3?[842,595]:[595,842]);const {width,height}=p.getSize();p.drawRectangle({x:0,y:height-180,width,height:180,color:lib.rgb(.06,.16,.21)});p.drawText('MUHAMMAD ARSALAN',{x:42,y:height-65,size:22,color:lib.rgb(1,1,1)});p.drawText(titles[i],{x:42,y:height-98,size:12,color:lib.rgb(.53,.86,.75)});p.drawText('IT Support / Operations / Practical AI',{x:42,y:height-126,size:10,color:lib.rgb(.75,.82,.87)});p.drawText(String(i+1).padStart(2,'0'),{x:width-75,y:height-62,size:28,color:lib.rgb(.53,.86,.75)});for(let j=0;j<4;j++){const y=height-230-j*95;p.drawText(['Overview','Selected experience','Tools and systems','Next steps'][j],{x:42,y,size:15,color:lib.rgb(.08,.22,.28)});p.drawText('A sample document for testing page layout and PDF export.',{x:42,y:y-22,size:10,color:lib.rgb(.35,.42,.47)});p.drawLine({start:{x:42,y:y-45},end:{x:width-42,y:y-45},thickness:1,color:lib.rgb(.85,.9,.91)});}p.drawText('WORKSPACE TEST DOCUMENT  /  '+(i+1),{x:42,y:28,size:8,color:lib.rgb(.4,.5,.55)});}
 fs.writeFileSync(out+'/sample.pdf',await doc.save());
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1512,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.PDF_WORKSPACE_URL || 'http://127.0.0.1:8765/resume-builder.html');await page.locator('[data-open-pdf-tools]').first().click();await page.screenshot({path:out+'/PDF_Workspace_Empty.png'});
 await page.locator('#pwFiles').setInputFiles(out+'/sample.pdf');await page.waitForFunction(()=>document.querySelectorAll('.pw-card').length===8&&!document.querySelector('#pdfToolsDialog').getAttribute('aria-busy').includes('true'));await page.waitForFunction(()=>document.querySelector('.pw-card canvas').height>500);
 await page.locator('.pw-card').nth(0).click();await page.locator('.pw-card').nth(2).click({modifiers:['Control']});await page.locator('.pw-sidebar [data-action="rotate"]').click();
 await page.locator('[data-action="addPane"]').click();await page.locator('.pw-card').nth(0).click();await page.locator('.pw-card').nth(2).click({modifiers:['Control']});await page.locator('#pwDestination').selectOption('doc-2');await page.locator('[data-action="move"]').click();
 assert.equal(await page.locator('.pw-pane').nth(0).locator('.pw-card').count(),6);assert.equal(await page.locator('.pw-pane').nth(1).locator('.pw-card').count(),2);
 await page.locator('[data-action="undo"]').click();assert.equal(await page.locator('.pw-pane').nth(0).locator('.pw-card').count(),8);await page.locator('[data-action="redo"]').click();
 await page.locator('.pw-pane').nth(0).locator('.pw-card').first().dragTo(page.locator('.pw-pane').nth(1).locator('.pw-card').first());assert.equal(await page.locator('.pw-pane').nth(1).locator('.pw-card').count(),3);
 await page.locator('#pwExportSource').selectOption('combined');await page.locator('#pwName').fill('Arsalan-Application');await page.locator('#pwExport').click();await page.locator('#pwDownload').waitFor({state:'visible'});const downloadPromise=page.waitForEvent('download');await page.locator('#pwDownload').click();const download=await downloadPromise;await download.saveAs(out+'/original-export.pdf');const output=await lib.PDFDocument.load(fs.readFileSync(out+'/original-export.pdf'));assert.equal(output.getPageCount(),8);assert.deepEqual(output.getPages().map(p=>p.getRotation().angle),[0,0,0,0,0,0,90,90]);
 await page.waitForTimeout(800);await page.screenshot({path:out+'/PDF_Workspace_Multiple_Documents.png'});
 await page.locator('.pw-pane').nth(1).locator('.pw-card-menu').first().click();await page.screenshot({path:out+'/PDF_Workspace_Page_Actions.png'});await page.keyboard.press('Escape');
 await page.locator('#pwQuality').selectOption('good');await page.locator('#pwPaper').selectOption('a4');await page.locator('#pwExport').click();await page.locator('#pwDownload').waitFor({state:'visible'});const d2=page.waitForEvent('download');await page.locator('#pwDownload').click();await(await d2).saveAs(out+'/good-export.pdf');const raster=await lib.PDFDocument.load(fs.readFileSync(out+'/good-export.pdf'));assert.equal(raster.getPageCount(),8);assert.ok(raster.getPages().every(p=>Math.abs(p.getWidth()-595.28)<1));
 await page.locator('#pwQuality').selectOption('original');await page.locator('#pwExport').click();await page.locator('#pwDownload').waitFor({state:'visible'});const d3=page.waitForEvent('download');await page.locator('#pwDownload').click();await(await d3).saveAs(out+'/a4-export.pdf');
 await page.locator('.pw-pane').nth(0).locator('.pw-card').first().dblclick();await page.waitForTimeout(500);await page.screenshot({path:out+'/PDF_Workspace_Preview.png'});await page.locator('[data-action="closePreview"]').click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/PDF_Workspace_Mobile.png'});assert.equal(await page.locator('#pdfToolsDialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);
 await page.setViewportSize({width:1512,height:1000});await page.locator('.pw-header [data-action="close"]').click();await page.locator('[data-open-pdf-tools]').first().click();assert.equal(await page.locator('.pw-card').count(),8);await page.locator('[data-action="reset"]').click();await page.locator('[data-action="confirmReset"]').click();assert.equal(await page.locator('.pw-card').count(),0);
 console.log(JSON.stringify({browserErrors:errors,passed:'Upload, previews, multi-selection, rotate, pane transfer, undo/redo, drag/drop, original and raster exports, A4 export, preview, mobile, close persistence and confirmed reset'}));assert.deepEqual(errors,[]);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
